<script lang="ts">
    import Pin from "$comps/form/pin.svelte";
</script>

<main id="main" class="grid justify-center margin-auto">
    <div class="authbox">
        <header class="authbox--header">
            <h1 class="authbox--title">Enter your Two-Factor code</h1>
            <p class="authbox--subtitle">
                It should be generated by your authenticator app, input it below:
            </p>
        </header>
        <form action="meow" class="authbox--form" method="post">
            <Pin />
            <p class="font-medium">
                Lost access to your authenticator? <a href="/auth/totp/recovery"
                    >Use a recovery code</a
                >
            </p>
        </form>
    </div>
</main>
