<script lang="ts">
    import * as AuthBox from "$comps/authBox";
    import Pin from "$comps/form/pin.svelte";
</script>

<AuthBox.Root>
    <AuthBox.Header
        title="Enter your Two-Factor code"
        subtitle="It should be generated by your authenticator app, input it below:"
    />
    <form action="meow" class="authbox--form" method="post">
        <Pin />
        <p class="font-medium">
            Lost access to your authenticator? <a href="/auth/totp/recovery">Use a recovery code</a>
        </p>
    </form>
</AuthBox.Root>
