services:
  database:
    image: "postgres:18-alpine"
    volumes:
      - "meow-db-data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: meow
      POSTGRES_PASSWORD: meow_pwd
      POSTGRES_DB: meow2_development

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - "mailpit-data:/data"
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  drizzle_gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    ports:
      - "4983:4983"
    volumes:
      - "drizzle-gateway-data:/app"
volumes:
  meow-db-data:
  mailpit-data:
  drizzle-gateway-data:
