/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type { ApiError, Passkey, RegisterPasskeyRequest, UlidId } from "../model";

export type registerPasskeyOptionsResponse200 = {
    data: void;
    status: 200;
};

export type registerPasskeyOptionsResponse401 = {
    data: ApiError;
    status: 401;
};

export type registerPasskeyOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type registerPasskeyOptionsResponseSuccess = registerPasskeyOptionsResponse200 & {
    headers: Headers;
};
export type registerPasskeyOptionsResponseError = (
    | registerPasskeyOptionsResponse401
    | registerPasskeyOptionsResponse500
) & {
    headers: Headers;
};

export type registerPasskeyOptionsResponse =
    | registerPasskeyOptionsResponseSuccess
    | registerPasskeyOptionsResponseError;

export const getRegisterPasskeyOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/me/webauthn`;
};

/**
 * @summary Get the passkey creation options
 */
export const registerPasskeyOptions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<registerPasskeyOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getRegisterPasskeyOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: registerPasskeyOptionsResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as registerPasskeyOptionsResponse;
};

export const getRegisterPasskeyOptionsMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof registerPasskeyOptions>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof registerPasskeyOptions>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["registerPasskeyOptions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof registerPasskeyOptions>>,
        void
    > = () => {
        return registerPasskeyOptions(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type RegisterPasskeyOptionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof registerPasskeyOptions>>
>;

export type RegisterPasskeyOptionsMutationError = ApiError;

/**
 * @summary Get the passkey creation options
 */
export const createRegisterPasskeyOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof registerPasskeyOptions>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof registerPasskeyOptions>>,
    TError,
    void,
    TContext
> => {
    return createMutation(
        () => ({ ...getRegisterPasskeyOptionsMutationOptions(options?.()) }),
        queryClient
    );
};
export type registerPasskeyExchangeResponse200 = {
    data: void;
    status: 200;
};

export type registerPasskeyExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type registerPasskeyExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type registerPasskeyExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type registerPasskeyExchangeResponseSuccess = registerPasskeyExchangeResponse200 & {
    headers: Headers;
};
export type registerPasskeyExchangeResponseError = (
    | registerPasskeyExchangeResponse401
    | registerPasskeyExchangeResponse404
    | registerPasskeyExchangeResponse500
) & {
    headers: Headers;
};

export type registerPasskeyExchangeResponse =
    | registerPasskeyExchangeResponseSuccess
    | registerPasskeyExchangeResponseError;

export const getRegisterPasskeyExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/me/webauthn/exchange`;
};

/**
 * @summary Exchange the passkey register result created on the browser
 */
export const registerPasskeyExchange = async (
    registerPasskeyRequest: RegisterPasskeyRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<registerPasskeyExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getRegisterPasskeyExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(registerPasskeyRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: registerPasskeyExchangeResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as registerPasskeyExchangeResponse;
};

export const getRegisterPasskeyExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof registerPasskeyExchange>>,
        TError,
        { data: RegisterPasskeyRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof registerPasskeyExchange>>,
    TError,
    { data: RegisterPasskeyRequest },
    TContext
> => {
    const mutationKey = ["registerPasskeyExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof registerPasskeyExchange>>,
        { data: RegisterPasskeyRequest }
    > = (props) => {
        const { data } = props ?? {};

        return registerPasskeyExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type RegisterPasskeyExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof registerPasskeyExchange>>
>;
export type RegisterPasskeyExchangeMutationBody = RegisterPasskeyRequest;
export type RegisterPasskeyExchangeMutationError = ApiError;

/**
 * @summary Exchange the passkey register result created on the browser
 */
export const createRegisterPasskeyExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof registerPasskeyExchange>>,
            TError,
            { data: RegisterPasskeyRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof registerPasskeyExchange>>,
    TError,
    { data: RegisterPasskeyRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getRegisterPasskeyExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type listPasskeysResponse200 = {
    data: Passkey[];
    status: 200;
};

export type listPasskeysResponse500 = {
    data: ApiError;
    status: 500;
};

export type listPasskeysResponseSuccess = listPasskeysResponse200 & {
    headers: Headers;
};
export type listPasskeysResponseError = listPasskeysResponse500 & {
    headers: Headers;
};

export type listPasskeysResponse = listPasskeysResponseSuccess | listPasskeysResponseError;

export const getListPasskeysUrl = () => {
    return `${apiUrlForOrval}/v1/me/webauthn/list`;
};

/**
 * @summary List all your created passkeys
 */
export const listPasskeys = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<listPasskeysResponse> => {
    const res = await (fetchFn ?? fetch)(getListPasskeysUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listPasskeysResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as listPasskeysResponse;
};

export const getListPasskeysQueryKey = () => {
    return [`${apiUrlForOrval}/v1/me/webauthn/list`] as const;
};

export const getListPasskeysQueryOptions = <
    TData = Awaited<ReturnType<typeof listPasskeys>>,
    TError = ApiError
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listPasskeys>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListPasskeysQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPasskeys>>> = ({ signal }) =>
        listPasskeys({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof listPasskeys>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListPasskeysQueryResult = NonNullable<Awaited<ReturnType<typeof listPasskeys>>>;
export type ListPasskeysQueryError = ApiError;

/**
 * @summary List all your created passkeys
 */

export function createListPasskeys<
    TData = Awaited<ReturnType<typeof listPasskeys>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof listPasskeys>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getListPasskeysQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type deletePasskeyResponse200 = {
    data: void;
    status: 200;
};

export type deletePasskeyResponse500 = {
    data: ApiError;
    status: 500;
};

export type deletePasskeyResponseSuccess = deletePasskeyResponse200 & {
    headers: Headers;
};
export type deletePasskeyResponseError = deletePasskeyResponse500 & {
    headers: Headers;
};

export type deletePasskeyResponse = deletePasskeyResponseSuccess | deletePasskeyResponseError;

export const getDeletePasskeyUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/webauthn/${id}`;
};

/**
 * You use the ID of one of your passkeys.
 * @summary Delete one of your passkeys
 */
export const deletePasskey = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<deletePasskeyResponse> => {
    const res = await (fetchFn ?? fetch)(getDeletePasskeyUrl(id), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deletePasskeyResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as deletePasskeyResponse;
};

export const getDeletePasskeyMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof deletePasskey>>,
        TError,
        { id: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof deletePasskey>>,
    TError,
    { id: UlidId },
    TContext
> => {
    const mutationKey = ["deletePasskey"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deletePasskey>>,
        { id: UlidId }
    > = (props) => {
        const { id } = props ?? {};

        return deletePasskey(id, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeletePasskeyMutationResult = NonNullable<Awaited<ReturnType<typeof deletePasskey>>>;

export type DeletePasskeyMutationError = ApiError;

/**
 * @summary Delete one of your passkeys
 */
export const createDeletePasskey = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof deletePasskey>>,
            TError,
            { id: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof deletePasskey>>,
    TError,
    { id: UlidId },
    TContext
> => {
    return createMutation(() => ({ ...getDeletePasskeyMutationOptions(options?.()) }), queryClient);
};
