/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { AlrightResponse } from "./alrightResponse.ts";
import type { FlowResponse } from "./flowResponse.ts";

export type _OtpExchangeResponse = FlowResponse | AlrightResponse;
