/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export type AdminListUsersParams = {
    /**
     * The id of the last item from the previous page. Normally provided in the `next` field of the previous response.
     */
    from?: null | UlidId;
    /**
     * If the total number of items should be returned.
     * @nullable
     */
    want_total?: boolean | null;
};
