/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type ApiErrorCodes = (typeof ApiErrorCodes)[keyof typeof ApiErrorCodes];

export const ApiErrorCodes = {
    OtpExpired: "OtpExpired",
    AlreadyAuthenticated: "AlreadyAuthenticated",
    Unauthenticated: "Unauthenticated",
    Meow: "Meow",
    Database: "Database",
    RouteDatabase: "RouteDatabase",
    InternalServerError: "InternalServerError",
    TotpAlreadyEnabled: "TotpAlreadyEnabled",
    TotpFlowNotFound: "TotpFlowNotFound",
    TotpNotEnabled: "TotpNotEnabled",
    TotpRecoveryAlreadyUsed: "TotpRecoveryAlreadyUsed",
    SudoNotEnabled: "SudoNotEnabled",
    SudoAlreadyEnabled: "SudoAlreadyEnabled",
    SudoOptionNotAvailable: "SudoOptionNotAvailable",
    AccountNotFound: "AccountNotFound",
    EmailAlreadyAssociated: "EmailAlreadyAssociated",
    LoginAlreadyAssociated: "LoginAlreadyAssociated",
    InvalidCode: "InvalidCode",
    WebauthnNotEnabled: "WebauthnNotEnabled",
    TotpRequiredEnabled: "TotpRequiredEnabled",
    WebauthnChallengeNotFound: "WebauthnChallengeNotFound",
    WebauthnError: "WebauthnError",
    Json: "Json",
    WebauthnCompromised: "WebauthnCompromised",
    MailerError: "MailerError",
    DataError: "DataError",
    JsonSyntaxError: "JsonSyntaxError",
    MissingJsonContentType: "MissingJsonContentType",
    FailedToBufferContent: "FailedToBufferContent",
    ValidationError: "ValidationError",
    AlreadyVerified: "AlreadyVerified",
    FlowNotFound: "FlowNotFound",
    NameChangeTooSoon: "NameChangeTooSoon",
    DataNotFound: "DataNotFound",
    ActionBlocked: "ActionBlocked",
    RatelimitExceeded: "RatelimitExceeded"
} as const;
