/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type ApplicationBuildProfile =
    (typeof ApplicationBuildProfile)[keyof typeof ApplicationBuildProfile];

export const ApplicationBuildProfile = {
    debug: "debug",
    release: "release"
} as const;
