/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { ApplicationBuildInfo } from "./applicationBuildInfo.ts";

export interface ApplicationInfoResponse {
    build: ApplicationBuildInfo;
    info: string;
    name: string;
    version: string;
}
