/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { ApplicationBuildProfile } from "./applicationBuildProfile.ts";

export interface ApplicationBuildInfo {
    build_time: string;
    git_hash: string;
    profile: ApplicationBuildProfile;
}
