/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export interface AuditLog {
    action: string;
    actor_id?: null | UlidId;
    /** @nullable */
    actor_login?: string | null;
    created_at: string;
    id: UlidId;
    metadata: unknown;
    user_id: UlidId;
    /** @nullable */
    user_login?: string | null;
    was_self: boolean;
}
