/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export interface AuditLog {
    action: string;
    actor_id?: UlidId | null;
    /** @nullable */
    actor_ip?: string | null;
    /** @nullable */
    actor_location?: string | null;
    /** @nullable */
    actor_login?: string | null;
    /** @nullable */
    actor_user_agent?: string | null;
    created_at: string;
    id: UlidId;
    metadata: unknown;
    resource_id?: UlidId | null;
    /** @nullable */
    resource_type?: string | null;
    user_id: UlidId;
    /** @nullable */
    user_login?: string | null;
    was_self: boolean;
}
