/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface AuthenticationPasskeyRequest {
    /** Unsigned Client processed extensions. */
    extensions?: unknown;
    /** The credential Id, likely base64 */
    id: string;
    /** The binary of the credential id. */
    rawId: unknown;
    /** The authenticator response. */
    response: unknown;
    /** The authenticator type. */
    type: string;
}
