/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod];

export const AuthMethod = {
    otp: "otp",
    totp: "totp",
    passkey: "passkey"
} as const;
