/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { CodeChallengeMethod } from "./codeChallengeMethod.ts";
import type { PromptType } from "./promptType.ts";
import type { ResponseType } from "./responseType.ts";
import type { UlidId } from "./ulidId.ts";

export interface AuthorizationRequest {
    client_id: UlidId;
    code_challenge: string;
    code_challenge_method: CodeChallengeMethod;
    /** @nullable */
    nonce?: string | null;
    prompt?: null | PromptType;
    /** @nullable */
    redirect_uri?: string | null;
    response_type: ResponseType;
    /** @nullable */
    scope?: string | null;
    /** @nullable */
    state?: string | null;
}
