/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type CodeChallengeMethod = (typeof CodeChallengeMethod)[keyof typeof CodeChallengeMethod];

export const CodeChallengeMethod = {
    plain: "plain",
    S256: "S256"
} as const;
