/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export interface ConsentMetadata {
    created_at: string;
    id: UlidId;
    name: string;
    old_scopes: number;
    redirect_url: string;
    scopes: number;
}
