/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface CreateTotpResponse {
    recovery_codes: string[];
    secret: string;
    uri: string;
}
