/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export interface ExchangeRequest {
    code: string;
    /** The flow ID used to identify and track a authentication flow */
    flow_id: UlidId;
}
