/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { AuthMethod } from "./authMethod.ts";

export interface FlowOptionResponse {
    /** The available authentication methods that an user can use to authenticate */
    methods: AuthMethod[];
}
