/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface FlowRequest {
    /** The email address of the user that is trying to authenticate */
    email: string;
}
