/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { AuthMethod } from "./authMethod.ts";
import type { UlidId } from "./ulidId.ts";

export interface FlowResponse {
    /** The flow ID used to identify and track this authentication flow */
    flow_id: UlidId;
    /** The next authentication method that can be used to finalize the authentication flow */
    next_method: AuthMethod[];
}
