/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type GrantType = (typeof GrantType)[keyof typeof GrantType];

export const GrantType = {
    authorization_code: "authorization_code",
    refresh_token: "refresh_token",
    client_credentials: "client_credentials"
} as const;
