/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type IdTokenSigningAlg = (typeof IdTokenSigningAlg)[keyof typeof IdTokenSigningAlg];

export const IdTokenSigningAlg = {
    ES256: "ES256",
    RS256: "RS256"
} as const;
