/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface JwkKey {
    alg: string;
    crv: string;
    kid: string;
    kty: string;
    use: string;
    x: string;
    y: string;
}
