/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { JwkKey } from "./jwkKey.ts";

export interface JwkKeySet {
    keys: JwkKey[];
}
