/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export type ListDataResponseSessionDataItem = {
    active_expires_at: string;
    created_at: string;
    expires_at: string;
    id: UlidId;
    updated_at: string;
};
