/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export type ListDataResponseUserDataItem = {
    created_at: string;
    email: string;
    flags: number;
    id: UlidId;
    login: string;
    updated_at: string;
};
