/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { ListDataResponseOauthApplicationDataItem } from "./listDataResponseOauthApplicationDataItem.ts";

export interface ListDataResponseOauthApplication {
    data: ListDataResponseOauthApplicationDataItem[];
    /** @nullable */
    next?: string | null;
    /** @nullable */
    total?: number | null;
}
