/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { ListDataResponseSessionDataItem } from "./listDataResponseSessionDataItem.ts";

export interface ListDataResponseSession {
    data: ListDataResponseSessionDataItem[];
    /** @nullable */
    next?: string | null;
    /** @nullable */
    total?: number | null;
}
