/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { ListDataResponseUserDataItem } from "./listDataResponseUserDataItem.ts";

export interface ListDataResponseUser {
    data: ListDataResponseUserDataItem[];
    /** @nullable */
    next?: string | null;
    /** @nullable */
    total?: number | null;
}
