/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { CodeChallengeMethod } from "./codeChallengeMethod.ts";
import type { GrantType } from "./grantType.ts";
import type { ResponseModes } from "./responseModes.ts";
import type { ResponseType } from "./responseType.ts";

export interface OauthMetadata {
    authorization_endpoint: string;
    code_challenge_methods_supported: CodeChallengeMethod[];
    grant_types_supported: GrantType[];
    issuer: string;
    jwks_uri: string;
    /** The way the client can send the response to related endpoints */
    response_modes_supported: ResponseModes[];
    response_types_supported: ResponseType[];
    scopes_supported: string[];
    token_endpoint: string;
}
