/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface OauthApplicationData {
    name: string;
    public: boolean;
    redirect_uri: string;
    scopes: number;
}
