/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { CodeChallengeMethod } from "./codeChallengeMethod.ts";
import type { GrantType } from "./grantType.ts";
import type { IdTokenSigningAlg } from "./idTokenSigningAlg.ts";
import type { ResponseModes } from "./responseModes.ts";
import type { ResponseType } from "./responseType.ts";
import type { SubjectTypes } from "./subjectTypes.ts";
import type { TokenAuthMethod } from "./tokenAuthMethod.ts";

export interface OpenIdMetadata {
    authorization_endpoint: string;
    code_challenge_methods_supported: CodeChallengeMethod[];
    grant_types_supported: GrantType[];
    /** The signing algorithms supported (JWKs) for the Id token to be signed with */
    id_token_signing_alg_values_supported: IdTokenSigningAlg[];
    issuer: string;
    jwks_uri: string;
    /** The way the client can send the response to related endpoints */
    response_modes_supported: ResponseModes[];
    response_types_supported: ResponseType[];
    scopes_supported: string[];
    subject_types_supported: SubjectTypes[];
    token_endpoint: string;
    /** The way to get the token by the client */
    token_endpoint_auth_methods_supported: TokenAuthMethod[];
    userinfo_endpoint: string;
}
