/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface OpenIdUserInfo {
    /** @nullable */
    email?: string | null;
    /** @nullable */
    email_verified?: boolean | null;
    /** @nullable */
    name?: string | null;
    sub: string;
}
