/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { UlidId } from "./ulidId.ts";

export interface Passkey {
    /**
     * The Authenticator Attestation GUID. An identifier used to determine the type of authenticator.
     * @nullable
     */
    aaguid?: string | null;
    created_at: string;
    /**
     * The point in time that the passkey was permanently disabled.
     * @nullable
     */
    disabled_at?: string | null;
    display_name: string;
    enabled: boolean;
    id: UlidId;
    /** @nullable */
    last_used_at?: string | null;
}
