/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type PromptType = (typeof PromptType)[keyof typeof PromptType];

export const PromptType = {
    none: "none",
    login: "login",
    consent: "consent",
    select_account: "select_account"
} as const;
