/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface PublicKeyCredentialStartOptions {
    /** The set of credentials that are allowed to sign this challenge. */
    allowCredentials: unknown[];
    /** The challenge that should be signed by the authenticator. */
    challenge: unknown;
    /** extensions. */
    extensions?: unknown;
    /**
     * Hints defining which types credentials may be used in this operation.
     * @nullable
     */
    hints?: unknown[] | null;
    /** The relying party ID. */
    rpId: string;
    /**
     * The timeout for the authenticator in case of no interaction.
     * @minimum 0
     * @nullable
     */
    timeout?: number | null;
    /** The verification policy the browser will request. */
    userVerification: unknown;
}
