/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface PublicKeyCredentialRegistrationOptions {
    /** The requested attestation level from the device. */
    attestation?: unknown;
    /**
     * The list of attestation formats that the RP will accept.
     * @nullable
     */
    attestationFormats?: unknown[] | null;
    /** Criteria defining which authenticators may be used in this operation. */
    authenticatorSelection?: unknown;
    /** The one-time challenge for the credential to sign. */
    challenge: unknown;
    /**
     * Credential ID's that are excluded from being able to be registered.
     * @nullable
     */
    excludeCredentials?: unknown[] | null;
    /** Non-standard extensions that may be used by the browser/authenticator. */
    extensions?: unknown;
    /**
     * Hints defining which credentials may be used in this operation.
     * @nullable
     */
    hints?: unknown[] | null;
    /** The set of cryptographic types allowed by this server. */
    pubKeyCredParams: unknown[];
    /** The relying party */
    rp: unknown;
    /**
     * The timeout for the authenticator to stop accepting the operation
     * @minimum 0
     * @nullable
     */
    timeout?: number | null;
    /** The user. */
    user: unknown;
}
