/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { PublicKeyCredentialRegistrationOptions } from "./publicKeyCredentialRegistrationOptions.ts";

export interface RegistrationChallengeResponse {
    /** The options. */
    publicKey: PublicKeyCredentialRegistrationOptions;
}
