/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface RegisterPasskeyRequest {
    /** Unsigned Client processed extensions. */
    extensions?: unknown;
    /** The id of the PublicKey credential, likely in base64. */
    id: string;
    /** The id of the credential, as binary. */
    rawId: unknown;
    /** <https://w3c.github.io/webauthn/#dom-publickeycredential-response> */
    response: unknown;
    /** The type of credential. */
    type: string;
}
