/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type ResponseType = (typeof ResponseType)[keyof typeof ResponseType];

export const ResponseType = {
    code: "code",
    token: "token"
} as const;
