/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type ResponseModes = (typeof ResponseModes)[keyof typeof ResponseModes];

export const ResponseModes = {
    query: "query",
    fragment: "fragment",
    form_post: "form_post"
} as const;
