/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { PublicKeyCredentialStartOptions } from "./publicKeyCredentialStartOptions.ts";

export interface StartChallengeResponse {
    /** The options. */
    publicKey: PublicKeyCredentialStartOptions;
}
