/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type SubjectTypes = (typeof SubjectTypes)[keyof typeof SubjectTypes];

export const SubjectTypes = {
    pairwise: "pairwise",
    public: "public"
} as const;
