/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { SudoOption } from "./sudoOption.ts";

export interface SudoOptionsResponse {
    options: SudoOption[];
}
