/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type SudoOption = (typeof SudoOption)[keyof typeof SudoOption];

export const SudoOption = {
    otp: "otp",
    totp: "totp",
    passkey: "passkey"
} as const;
