/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type TokenAuthMethod = (typeof TokenAuthMethod)[keyof typeof TokenAuthMethod];

export const TokenAuthMethod = {
    client_secret_post: "client_secret_post",
    client_secret_basic: "client_secret_basic",
    client_secret_jwt: "client_secret_jwt",
    private_key_jwt: "private_key_jwt"
} as const;
