/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { GrantType } from "./grantType.ts";
import type { UlidId } from "./ulidId.ts";

export interface TokenRequest {
    client_id: UlidId;
    client_secret: string;
    code: string;
    code_verifier: string;
    grant_type: GrantType;
    redirect_uri: string;
}
