/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export type TokenType = (typeof TokenType)[keyof typeof TokenType];

export const TokenType = {
    bearer: "bearer",
    mac: "mac"
} as const;
