/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import type { TokenType } from "./tokenType.ts";

export interface TokenResponse {
    access_token: string;
    expires_in: number;
    /** @nullable */
    id_token?: string | null;
    scope: string;
    token_type: TokenType;
}
