/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */

export interface UserUpdateRequest {
    /** @nullable */
    email?: string | null;
    /** @nullable */
    flags?: number | null;
    /** @nullable */
    name?: string | null;
}
