[logging]
enabled = true
level = "info"

[http]
bind = "127.0.0.1:8080"
origin = "http://localhost:8080/"

[http.api_docs]
enabled = true
path = "/scalar"

[database]
url = "postgres://meow:meow_pwd@localhost:5432/meow2_development"
min_connections = 1
max_connections = 10

[session]
cookie_name = "meow_sess"
secret_key = "12009604c248308c35a8609807c2d139f5fa585d252ea8de33752d2216e55508"
expire_age_seconds = 2592000
active_expire_age_seconds = 604800
update_threshold_seconds = 600
sudo_expire_age_seconds = 900

[mailer]
smtp_host = "localhost"
smtp_username = ""
smtp_password = ""
smtp_port = 1025
smtp_secure = false
from_email = "meow@meow.com"
test_connection = false

[application]
shutdown_timeout_seconds = 120
shutdown_timeout_enabled = true

[totp]
issuer = "meow_auth"
encryption_secret = "852f529daf9b8b19413ef070a3252ed5aa281ef1b38c59debfebeb8aec6bb0d9"
digits = 6

[webauthn]
rp_id = "localhost"
rp_name = "MeowAuth"
timeout_seconds = 300
