[application]
shutdown_timeout_seconds = 120
shutdown_timeout_enabled = true
master_key = "df2f3ba178ecaa9968c042e230661d668e96f73881da2968a525af802d72692c"

[http]
bind = "127.0.0.1:8080"
origin = "http://localhost:8080/"
frontend = "http://localhost:3000/"

[http.api_docs]
enabled = true
path = "/scalar"

[database]
url = "postgres://meow:meow_pwd@localhost:5432/meow2_development"
min_connections = 1
max_connections = 10

[logging]
enabled = true
level = "info"

[mailer]
smtp_host = "localhost"
smtp_username = ""
smtp_password = ""
smtp_port = 1025
smtp_secure = false
from_email = "meow@meow.com"
test_connection = false

[session]
cookie_name = "meow_sess"
expire_age_seconds = 2592000
active_expire_age_seconds = 604800
update_threshold_seconds = 600
sudo_expire_age_seconds = 900

[totp]
issuer = "meow_auth"
digits = 6

[webauthn]
rp_id = "localhost"
rp_display_name = "MeowAuth"
timeout_seconds = 300

[oauth]
oidc_id_token_expire_seconds = 3600
jwk_active_seconds = 5184000
jwk_expired_after_seconds = 7776000
jwk_cycle_after_seconds = 43200
