/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type {
    AdminListUsersParams,
    AlrightResponse,
    ApiError,
    AuditLog,
    ListDataResponseOauthApplication,
    ListDataResponseSession,
    ListDataResponseUser,
    OauthApplicationData,
    OauthApplicationDataResponse,
    UlidId,
    User,
    UserUpdateRequest
} from "../model";

export type adminListUsersResponse200 = {
    data: ListDataResponseUser;
    status: 200;
};

export type adminListUsersResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminListUsersResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminListUsersResponseSuccess = adminListUsersResponse200 & {
    headers: Headers;
};
export type adminListUsersResponseError = (
    | adminListUsersResponse403
    | adminListUsersResponse500
) & {
    headers: Headers;
};

export type adminListUsersResponse = adminListUsersResponseSuccess | adminListUsersResponseError;

export const getAdminListUsersUrl = (params?: AdminListUsersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `${apiUrlForOrval}/v1/admin/users/list?${stringifiedParams}`
        : `${apiUrlForOrval}/v1/admin/users/list`;
};

/**
 * @summary List registered users
 */
export const adminListUsers = async (
    params?: AdminListUsersParams,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminListUsersResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminListUsersUrl(params), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminListUsersResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminListUsersResponse;
};

export const getAdminListUsersQueryKey = (params?: AdminListUsersParams) => {
    return [`${apiUrlForOrval}/v1/admin/users/list`, ...(params ? [params] : [])] as const;
};

export const getAdminListUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ApiError
>(
    params?: AdminListUsersParams,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminListUsersQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListUsers>>> = ({ signal }) =>
        adminListUsers(params, { signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof adminListUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListUsers>>>;
export type AdminListUsersQueryError = ApiError;

/**
 * @summary List registered users
 */

export function createAdminListUsers<
    TData = Awaited<ReturnType<typeof adminListUsers>>,
    TError = ApiError
>(
    params?: () => AdminListUsersParams,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAdminListUsersQueryOptions(params?.(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type adminInfoUserResponse200 = {
    data: User;
    status: 200;
};

export type adminInfoUserResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminInfoUserResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminInfoUserResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminInfoUserResponseSuccess = adminInfoUserResponse200 & {
    headers: Headers;
};
export type adminInfoUserResponseError = (
    | adminInfoUserResponse403
    | adminInfoUserResponse404
    | adminInfoUserResponse500
) & {
    headers: Headers;
};

export type adminInfoUserResponse = adminInfoUserResponseSuccess | adminInfoUserResponseError;

export const getAdminInfoUserUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}`;
};

/**
 * @summary Get info about a user
 */
export const adminInfoUser = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminInfoUserResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminInfoUserUrl(id), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminInfoUserResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminInfoUserResponse;
};

export const getAdminInfoUserQueryKey = (id: UlidId) => {
    return [`${apiUrlForOrval}/v1/admin/users/${id}`] as const;
};

export const getAdminInfoUserQueryOptions = <
    TData = Awaited<ReturnType<typeof adminInfoUser>>,
    TError = ApiError
>(
    id: UlidId,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminInfoUser>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminInfoUserQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminInfoUser>>> = ({ signal }) =>
        adminInfoUser(id, { signal, ...fetchOptions }, fetcherFn);

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions
    } as CreateQueryOptions<Awaited<ReturnType<typeof adminInfoUser>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type AdminInfoUserQueryResult = NonNullable<Awaited<ReturnType<typeof adminInfoUser>>>;
export type AdminInfoUserQueryError = ApiError;

/**
 * @summary Get info about a user
 */

export function createAdminInfoUser<
    TData = Awaited<ReturnType<typeof adminInfoUser>>,
    TError = ApiError
>(
    id: () => UlidId,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminInfoUser>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAdminInfoUserQueryOptions(id(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type adminEditUserResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type adminEditUserResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminEditUserResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminEditUserResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminEditUserResponseSuccess = adminEditUserResponse200 & {
    headers: Headers;
};
export type adminEditUserResponseError = (
    | adminEditUserResponse403
    | adminEditUserResponse404
    | adminEditUserResponse500
) & {
    headers: Headers;
};

export type adminEditUserResponse = adminEditUserResponseSuccess | adminEditUserResponseError;

export const getAdminEditUserUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}`;
};

/**
 * @summary Update an existing user
 */
export const adminEditUser = async (
    id: UlidId,
    userUpdateRequest: UserUpdateRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminEditUserResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminEditUserUrl(id), {
        credentials: "include",
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(userUpdateRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminEditUserResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminEditUserResponse;
};

export const getAdminEditUserMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminEditUser>>,
        TError,
        { id: UlidId; data: UserUpdateRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminEditUser>>,
    TError,
    { id: UlidId; data: UserUpdateRequest },
    TContext
> => {
    const mutationKey = ["adminEditUser"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminEditUser>>,
        { id: UlidId; data: UserUpdateRequest }
    > = (props) => {
        const { id, data } = props ?? {};

        return adminEditUser(id, data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminEditUserMutationResult = NonNullable<Awaited<ReturnType<typeof adminEditUser>>>;
export type AdminEditUserMutationBody = UserUpdateRequest;
export type AdminEditUserMutationError = ApiError;

/**
 * @summary Update an existing user
 */
export const createAdminEditUser = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminEditUser>>,
            TError,
            { id: UlidId; data: UserUpdateRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminEditUser>>,
    TError,
    { id: UlidId; data: UserUpdateRequest },
    TContext
> => {
    return createMutation(() => ({ ...getAdminEditUserMutationOptions(options?.()) }), queryClient);
};
export type adminUserAuditLogResponse200 = {
    data: AuditLog;
    status: 200;
};

export type adminUserAuditLogResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminUserAuditLogResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminUserAuditLogResponseSuccess = adminUserAuditLogResponse200 & {
    headers: Headers;
};
export type adminUserAuditLogResponseError = (
    | adminUserAuditLogResponse403
    | adminUserAuditLogResponse500
) & {
    headers: Headers;
};

export type adminUserAuditLogResponse =
    | adminUserAuditLogResponseSuccess
    | adminUserAuditLogResponseError;

export const getAdminUserAuditLogUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/audit`;
};

/**
 * @summary Get a user's audit log
 */
export const adminUserAuditLog = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminUserAuditLogResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminUserAuditLogUrl(id), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminUserAuditLogResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminUserAuditLogResponse;
};

export const getAdminUserAuditLogQueryKey = (id: UlidId) => {
    return [`${apiUrlForOrval}/v1/admin/users/${id}/audit`] as const;
};

export const getAdminUserAuditLogQueryOptions = <
    TData = Awaited<ReturnType<typeof adminUserAuditLog>>,
    TError = ApiError
>(
    id: UlidId,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminUserAuditLog>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminUserAuditLogQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminUserAuditLog>>> = ({ signal }) =>
        adminUserAuditLog(id, { signal, ...fetchOptions }, fetcherFn);

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions
    } as CreateQueryOptions<Awaited<ReturnType<typeof adminUserAuditLog>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type AdminUserAuditLogQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminUserAuditLog>>
>;
export type AdminUserAuditLogQueryError = ApiError;

/**
 * @summary Get a user's audit log
 */

export function createAdminUserAuditLog<
    TData = Awaited<ReturnType<typeof adminUserAuditLog>>,
    TError = ApiError
>(
    id: () => UlidId,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminUserAuditLog>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAdminUserAuditLogQueryOptions(id(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type adminListUserApplicationsResponse200 = {
    data: ListDataResponseOauthApplication;
    status: 200;
};

export type adminListUserApplicationsResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminListUserApplicationsResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminListUserApplicationsResponseSuccess = adminListUserApplicationsResponse200 & {
    headers: Headers;
};
export type adminListUserApplicationsResponseError = (
    | adminListUserApplicationsResponse403
    | adminListUserApplicationsResponse500
) & {
    headers: Headers;
};

export type adminListUserApplicationsResponse =
    | adminListUserApplicationsResponseSuccess
    | adminListUserApplicationsResponseError;

export const getAdminListUserApplicationsUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/application/list`;
};

/**
 * @summary List oauth applications of a user
 */
export const adminListUserApplications = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminListUserApplicationsResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminListUserApplicationsUrl(id), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminListUserApplicationsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminListUserApplicationsResponse;
};

export const getAdminListUserApplicationsQueryKey = (id: UlidId) => {
    return [`${apiUrlForOrval}/v1/admin/users/${id}/oauth/application/list`] as const;
};

export const getAdminListUserApplicationsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListUserApplications>>,
    TError = ApiError
>(
    id: UlidId,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminListUserApplications>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminListUserApplicationsQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListUserApplications>>> = ({
        signal
    }) => adminListUserApplications(id, { signal, ...fetchOptions }, fetcherFn);

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions
    } as CreateQueryOptions<
        Awaited<ReturnType<typeof adminListUserApplications>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListUserApplicationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListUserApplications>>
>;
export type AdminListUserApplicationsQueryError = ApiError;

/**
 * @summary List oauth applications of a user
 */

export function createAdminListUserApplications<
    TData = Awaited<ReturnType<typeof adminListUserApplications>>,
    TError = ApiError
>(
    id: () => UlidId,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminListUserApplications>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAdminListUserApplicationsQueryOptions(id(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type adminDeleteUserApplicationResponse200 = {
    data: void;
    status: 200;
};

export type adminDeleteUserApplicationResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminDeleteUserApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminDeleteUserApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminDeleteUserApplicationResponseSuccess = adminDeleteUserApplicationResponse200 & {
    headers: Headers;
};
export type adminDeleteUserApplicationResponseError = (
    | adminDeleteUserApplicationResponse403
    | adminDeleteUserApplicationResponse404
    | adminDeleteUserApplicationResponse500
) & {
    headers: Headers;
};

export type adminDeleteUserApplicationResponse =
    | adminDeleteUserApplicationResponseSuccess
    | adminDeleteUserApplicationResponseError;

export const getAdminDeleteUserApplicationUrl = (id: UlidId, cid: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/application/${cid}`;
};

/**
 * @summary Delete an existing oauth application
 */
export const adminDeleteUserApplication = async (
    id: UlidId,
    cid: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminDeleteUserApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminDeleteUserApplicationUrl(id, cid), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminDeleteUserApplicationResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as adminDeleteUserApplicationResponse;
};

export const getAdminDeleteUserApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminDeleteUserApplication>>,
        TError,
        { id: UlidId; cid: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminDeleteUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    const mutationKey = ["adminDeleteUserApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminDeleteUserApplication>>,
        { id: UlidId; cid: UlidId }
    > = (props) => {
        const { id, cid } = props ?? {};

        return adminDeleteUserApplication(id, cid, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminDeleteUserApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminDeleteUserApplication>>
>;

export type AdminDeleteUserApplicationMutationError = ApiError;

/**
 * @summary Delete an existing oauth application
 */
export const createAdminDeleteUserApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminDeleteUserApplication>>,
            TError,
            { id: UlidId; cid: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminDeleteUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminDeleteUserApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type adminEditUserApplicationResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type adminEditUserApplicationResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminEditUserApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminEditUserApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminEditUserApplicationResponseSuccess = adminEditUserApplicationResponse200 & {
    headers: Headers;
};
export type adminEditUserApplicationResponseError = (
    | adminEditUserApplicationResponse403
    | adminEditUserApplicationResponse404
    | adminEditUserApplicationResponse500
) & {
    headers: Headers;
};

export type adminEditUserApplicationResponse =
    | adminEditUserApplicationResponseSuccess
    | adminEditUserApplicationResponseError;

export const getAdminEditUserApplicationUrl = (id: UlidId, cid: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/application/${cid}`;
};

/**
 * @summary Update an existing oauth application
 */
export const adminEditUserApplication = async (
    id: UlidId,
    cid: UlidId,
    oauthApplicationData: OauthApplicationData,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminEditUserApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminEditUserApplicationUrl(id, cid), {
        credentials: "include",
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(oauthApplicationData)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminEditUserApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminEditUserApplicationResponse;
};

export const getAdminEditUserApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminEditUserApplication>>,
        TError,
        { id: UlidId; cid: UlidId; data: OauthApplicationData },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminEditUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId; data: OauthApplicationData },
    TContext
> => {
    const mutationKey = ["adminEditUserApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminEditUserApplication>>,
        { id: UlidId; cid: UlidId; data: OauthApplicationData }
    > = (props) => {
        const { id, cid, data } = props ?? {};

        return adminEditUserApplication(id, cid, data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminEditUserApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminEditUserApplication>>
>;
export type AdminEditUserApplicationMutationBody = OauthApplicationData;
export type AdminEditUserApplicationMutationError = ApiError;

/**
 * @summary Update an existing oauth application
 */
export const createAdminEditUserApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminEditUserApplication>>,
            TError,
            { id: UlidId; cid: UlidId; data: OauthApplicationData },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminEditUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId; data: OauthApplicationData },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminEditUserApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type adminRevokeAllAuthUserApplicationResponse200 = {
    data: OauthApplicationDataResponse;
    status: 200;
};

export type adminRevokeAllAuthUserApplicationResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminRevokeAllAuthUserApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminRevokeAllAuthUserApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminRevokeAllAuthUserApplicationResponseSuccess =
    adminRevokeAllAuthUserApplicationResponse200 & {
        headers: Headers;
    };
export type adminRevokeAllAuthUserApplicationResponseError = (
    | adminRevokeAllAuthUserApplicationResponse403
    | adminRevokeAllAuthUserApplicationResponse404
    | adminRevokeAllAuthUserApplicationResponse500
) & {
    headers: Headers;
};

export type adminRevokeAllAuthUserApplicationResponse =
    | adminRevokeAllAuthUserApplicationResponseSuccess
    | adminRevokeAllAuthUserApplicationResponseError;

export const getAdminRevokeAllAuthUserApplicationUrl = (id: UlidId, cid: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/application/${cid}/revoke_authorizations`;
};

/**
 * @summary Revoke all authorizations of an existing oauth application
 */
export const adminRevokeAllAuthUserApplication = async (
    id: UlidId,
    cid: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminRevokeAllAuthUserApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminRevokeAllAuthUserApplicationUrl(id, cid), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminRevokeAllAuthUserApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers
    } as adminRevokeAllAuthUserApplicationResponse;
};

export const getAdminRevokeAllAuthUserApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminRevokeAllAuthUserApplication>>,
        TError,
        { id: UlidId; cid: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminRevokeAllAuthUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    const mutationKey = ["adminRevokeAllAuthUserApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminRevokeAllAuthUserApplication>>,
        { id: UlidId; cid: UlidId }
    > = (props) => {
        const { id, cid } = props ?? {};

        return adminRevokeAllAuthUserApplication(id, cid, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminRevokeAllAuthUserApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminRevokeAllAuthUserApplication>>
>;

export type AdminRevokeAllAuthUserApplicationMutationError = ApiError;

/**
 * @summary Revoke all authorizations of an existing oauth application
 */
export const createAdminRevokeAllAuthUserApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminRevokeAllAuthUserApplication>>,
            TError,
            { id: UlidId; cid: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminRevokeAllAuthUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminRevokeAllAuthUserApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type adminRotateSecretUserApplicationResponse200 = {
    data: OauthApplicationDataResponse;
    status: 200;
};

export type adminRotateSecretUserApplicationResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminRotateSecretUserApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminRotateSecretUserApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminRotateSecretUserApplicationResponseSuccess =
    adminRotateSecretUserApplicationResponse200 & {
        headers: Headers;
    };
export type adminRotateSecretUserApplicationResponseError = (
    | adminRotateSecretUserApplicationResponse403
    | adminRotateSecretUserApplicationResponse404
    | adminRotateSecretUserApplicationResponse500
) & {
    headers: Headers;
};

export type adminRotateSecretUserApplicationResponse =
    | adminRotateSecretUserApplicationResponseSuccess
    | adminRotateSecretUserApplicationResponseError;

export const getAdminRotateSecretUserApplicationUrl = (id: UlidId, cid: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/application/${cid}/rotate_keys`;
};

/**
 * @summary Rotate the secret of an existing oauth application
 */
export const adminRotateSecretUserApplication = async (
    id: UlidId,
    cid: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminRotateSecretUserApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminRotateSecretUserApplicationUrl(id, cid), {
        credentials: "include",
        ...options,
        method: "PATCH"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminRotateSecretUserApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers
    } as adminRotateSecretUserApplicationResponse;
};

export const getAdminRotateSecretUserApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminRotateSecretUserApplication>>,
        TError,
        { id: UlidId; cid: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminRotateSecretUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    const mutationKey = ["adminRotateSecretUserApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminRotateSecretUserApplication>>,
        { id: UlidId; cid: UlidId }
    > = (props) => {
        const { id, cid } = props ?? {};

        return adminRotateSecretUserApplication(id, cid, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminRotateSecretUserApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminRotateSecretUserApplication>>
>;

export type AdminRotateSecretUserApplicationMutationError = ApiError;

/**
 * @summary Rotate the secret of an existing oauth application
 */
export const createAdminRotateSecretUserApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminRotateSecretUserApplication>>,
            TError,
            { id: UlidId; cid: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminRotateSecretUserApplication>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminRotateSecretUserApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type adminListUserOauthAuthorizationsResponse200 = {
    data: ListDataResponseOauthApplication;
    status: 200;
};

export type adminListUserOauthAuthorizationsResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminListUserOauthAuthorizationsResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminListUserOauthAuthorizationsResponseSuccess =
    adminListUserOauthAuthorizationsResponse200 & {
        headers: Headers;
    };
export type adminListUserOauthAuthorizationsResponseError = (
    | adminListUserOauthAuthorizationsResponse403
    | adminListUserOauthAuthorizationsResponse500
) & {
    headers: Headers;
};

export type adminListUserOauthAuthorizationsResponse =
    | adminListUserOauthAuthorizationsResponseSuccess
    | adminListUserOauthAuthorizationsResponseError;

export const getAdminListUserOauthAuthorizationsUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/authorization/list`;
};

/**
 * @summary List oauth authorizations of a user
 */
export const adminListUserOauthAuthorizations = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminListUserOauthAuthorizationsResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminListUserOauthAuthorizationsUrl(id), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminListUserOauthAuthorizationsResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers
    } as adminListUserOauthAuthorizationsResponse;
};

export const getAdminListUserOauthAuthorizationsQueryKey = (id: UlidId) => {
    return [`${apiUrlForOrval}/v1/admin/users/${id}/oauth/authorization/list`] as const;
};

export const getAdminListUserOauthAuthorizationsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>,
    TError = ApiError
>(
    id: UlidId,
    options?: {
        query?: Partial<
            CreateQueryOptions<
                Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminListUserOauthAuthorizationsQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>> = ({
        signal
    }) => adminListUserOauthAuthorizations(id, { signal, ...fetchOptions }, fetcherFn);

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions
    } as CreateQueryOptions<
        Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AdminListUserOauthAuthorizationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>
>;
export type AdminListUserOauthAuthorizationsQueryError = ApiError;

/**
 * @summary List oauth authorizations of a user
 */

export function createAdminListUserOauthAuthorizations<
    TData = Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>,
    TError = ApiError
>(
    id: () => UlidId,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<
                Awaited<ReturnType<typeof adminListUserOauthAuthorizations>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAdminListUserOauthAuthorizationsQueryOptions(id(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type adminDeleteUserOauthAuthorizationResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type adminDeleteUserOauthAuthorizationResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminDeleteUserOauthAuthorizationResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminDeleteUserOauthAuthorizationResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminDeleteUserOauthAuthorizationResponseSuccess =
    adminDeleteUserOauthAuthorizationResponse200 & {
        headers: Headers;
    };
export type adminDeleteUserOauthAuthorizationResponseError = (
    | adminDeleteUserOauthAuthorizationResponse403
    | adminDeleteUserOauthAuthorizationResponse404
    | adminDeleteUserOauthAuthorizationResponse500
) & {
    headers: Headers;
};

export type adminDeleteUserOauthAuthorizationResponse =
    | adminDeleteUserOauthAuthorizationResponseSuccess
    | adminDeleteUserOauthAuthorizationResponseError;

export const getAdminDeleteUserOauthAuthorizationUrl = (id: UlidId, cid: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/oauth/authorization/${cid}`;
};

/**
 * @summary Revoke an oauth authorization
 */
export const adminDeleteUserOauthAuthorization = async (
    id: UlidId,
    cid: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminDeleteUserOauthAuthorizationResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminDeleteUserOauthAuthorizationUrl(id, cid), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminDeleteUserOauthAuthorizationResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers
    } as adminDeleteUserOauthAuthorizationResponse;
};

export const getAdminDeleteUserOauthAuthorizationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminDeleteUserOauthAuthorization>>,
        TError,
        { id: UlidId; cid: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminDeleteUserOauthAuthorization>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    const mutationKey = ["adminDeleteUserOauthAuthorization"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminDeleteUserOauthAuthorization>>,
        { id: UlidId; cid: UlidId }
    > = (props) => {
        const { id, cid } = props ?? {};

        return adminDeleteUserOauthAuthorization(id, cid, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminDeleteUserOauthAuthorizationMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminDeleteUserOauthAuthorization>>
>;

export type AdminDeleteUserOauthAuthorizationMutationError = ApiError;

/**
 * @summary Revoke an oauth authorization
 */
export const createAdminDeleteUserOauthAuthorization = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminDeleteUserOauthAuthorization>>,
            TError,
            { id: UlidId; cid: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminDeleteUserOauthAuthorization>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminDeleteUserOauthAuthorizationMutationOptions(options?.()) }),
        queryClient
    );
};
export type adminRevokeAllUserSessionsResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type adminRevokeAllUserSessionsResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminRevokeAllUserSessionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminRevokeAllUserSessionsResponseSuccess = adminRevokeAllUserSessionsResponse200 & {
    headers: Headers;
};
export type adminRevokeAllUserSessionsResponseError = (
    | adminRevokeAllUserSessionsResponse403
    | adminRevokeAllUserSessionsResponse500
) & {
    headers: Headers;
};

export type adminRevokeAllUserSessionsResponse =
    | adminRevokeAllUserSessionsResponseSuccess
    | adminRevokeAllUserSessionsResponseError;

export const getAdminRevokeAllUserSessionsUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/session`;
};

/**
 * @summary Revoke all user sessions
 */
export const adminRevokeAllUserSessions = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminRevokeAllUserSessionsResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminRevokeAllUserSessionsUrl(id), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminRevokeAllUserSessionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminRevokeAllUserSessionsResponse;
};

export const getAdminRevokeAllUserSessionsMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminRevokeAllUserSessions>>,
        TError,
        { id: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminRevokeAllUserSessions>>,
    TError,
    { id: UlidId },
    TContext
> => {
    const mutationKey = ["adminRevokeAllUserSessions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminRevokeAllUserSessions>>,
        { id: UlidId }
    > = (props) => {
        const { id } = props ?? {};

        return adminRevokeAllUserSessions(id, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminRevokeAllUserSessionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminRevokeAllUserSessions>>
>;

export type AdminRevokeAllUserSessionsMutationError = ApiError;

/**
 * @summary Revoke all user sessions
 */
export const createAdminRevokeAllUserSessions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminRevokeAllUserSessions>>,
            TError,
            { id: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminRevokeAllUserSessions>>,
    TError,
    { id: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminRevokeAllUserSessionsMutationOptions(options?.()) }),
        queryClient
    );
};
export type adminListUserSessionsResponse200 = {
    data: ListDataResponseSession;
    status: 200;
};

export type adminListUserSessionsResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminListUserSessionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminListUserSessionsResponseSuccess = adminListUserSessionsResponse200 & {
    headers: Headers;
};
export type adminListUserSessionsResponseError = (
    | adminListUserSessionsResponse403
    | adminListUserSessionsResponse500
) & {
    headers: Headers;
};

export type adminListUserSessionsResponse =
    | adminListUserSessionsResponseSuccess
    | adminListUserSessionsResponseError;

export const getAdminListUserSessionsUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/session/list`;
};

/**
 * @summary List sessions of a user
 */
export const adminListUserSessions = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminListUserSessionsResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminListUserSessionsUrl(id), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminListUserSessionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminListUserSessionsResponse;
};

export const getAdminListUserSessionsQueryKey = (id: UlidId) => {
    return [`${apiUrlForOrval}/v1/admin/users/${id}/session/list`] as const;
};

export const getAdminListUserSessionsQueryOptions = <
    TData = Awaited<ReturnType<typeof adminListUserSessions>>,
    TError = ApiError
>(
    id: UlidId,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminListUserSessions>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAdminListUserSessionsQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListUserSessions>>> = ({
        signal
    }) => adminListUserSessions(id, { signal, ...fetchOptions }, fetcherFn);

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions
    } as CreateQueryOptions<Awaited<ReturnType<typeof adminListUserSessions>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type AdminListUserSessionsQueryResult = NonNullable<
    Awaited<ReturnType<typeof adminListUserSessions>>
>;
export type AdminListUserSessionsQueryError = ApiError;

/**
 * @summary List sessions of a user
 */

export function createAdminListUserSessions<
    TData = Awaited<ReturnType<typeof adminListUserSessions>>,
    TError = ApiError
>(
    id: () => UlidId,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof adminListUserSessions>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAdminListUserSessionsQueryOptions(id(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type adminRevokeUserSessionResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type adminRevokeUserSessionResponse403 = {
    data: ApiError;
    status: 403;
};

export type adminRevokeUserSessionResponse404 = {
    data: ApiError;
    status: 404;
};

export type adminRevokeUserSessionResponse500 = {
    data: ApiError;
    status: 500;
};

export type adminRevokeUserSessionResponseSuccess = adminRevokeUserSessionResponse200 & {
    headers: Headers;
};
export type adminRevokeUserSessionResponseError = (
    | adminRevokeUserSessionResponse403
    | adminRevokeUserSessionResponse404
    | adminRevokeUserSessionResponse500
) & {
    headers: Headers;
};

export type adminRevokeUserSessionResponse =
    | adminRevokeUserSessionResponseSuccess
    | adminRevokeUserSessionResponseError;

export const getAdminRevokeUserSessionUrl = (id: UlidId, cid: UlidId) => {
    return `${apiUrlForOrval}/v1/admin/users/${id}/session/${cid}`;
};

/**
 * @summary Revoke a user session
 */
export const adminRevokeUserSession = async (
    id: UlidId,
    cid: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<adminRevokeUserSessionResponse> => {
    const res = await (fetchFn ?? fetch)(getAdminRevokeUserSessionUrl(id, cid), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: adminRevokeUserSessionResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as adminRevokeUserSessionResponse;
};

export const getAdminRevokeUserSessionMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof adminRevokeUserSession>>,
        TError,
        { id: UlidId; cid: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof adminRevokeUserSession>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    const mutationKey = ["adminRevokeUserSession"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof adminRevokeUserSession>>,
        { id: UlidId; cid: UlidId }
    > = (props) => {
        const { id, cid } = props ?? {};

        return adminRevokeUserSession(id, cid, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type AdminRevokeUserSessionMutationResult = NonNullable<
    Awaited<ReturnType<typeof adminRevokeUserSession>>
>;

export type AdminRevokeUserSessionMutationError = ApiError;

/**
 * @summary Revoke a user session
 */
export const createAdminRevokeUserSession = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof adminRevokeUserSession>>,
            TError,
            { id: UlidId; cid: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof adminRevokeUserSession>>,
    TError,
    { id: UlidId; cid: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getAdminRevokeUserSessionMutationOptions(options?.()) }),
        queryClient
    );
};
