/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createQuery } from "@tanstack/svelte-query";
import type {
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type { AlrightResponse, ApplicationInfoResponse } from "../model";

export type applicationInfoResponse200 = {
    data: ApplicationInfoResponse;
    status: 200;
};

export type applicationInfoResponseSuccess = applicationInfoResponse200 & {
    headers: Headers;
};

export type applicationInfoResponse = applicationInfoResponseSuccess;

export const getApplicationInfoUrl = () => {
    return `${apiUrlForOrval}/`;
};

/**
 * @summary Info about the application
 */
export const applicationInfo = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<applicationInfoResponse> => {
    const res = await (fetchFn ?? fetch)(getApplicationInfoUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: applicationInfoResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as applicationInfoResponse;
};

export const getApplicationInfoQueryKey = () => {
    return [`${apiUrlForOrval}/`] as const;
};

export const getApplicationInfoQueryOptions = <
    TData = Awaited<ReturnType<typeof applicationInfo>>,
    TError = unknown
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof applicationInfo>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getApplicationInfoQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof applicationInfo>>> = ({ signal }) =>
        applicationInfo({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof applicationInfo>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ApplicationInfoQueryResult = NonNullable<Awaited<ReturnType<typeof applicationInfo>>>;
export type ApplicationInfoQueryError = unknown;

/**
 * @summary Info about the application
 */

export function createApplicationInfo<
    TData = Awaited<ReturnType<typeof applicationInfo>>,
    TError = unknown
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof applicationInfo>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getApplicationInfoQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type healthResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type healthResponseSuccess = healthResponse200 & {
    headers: Headers;
};

export type healthResponse = healthResponseSuccess;

export const getHealthUrl = () => {
    return `${apiUrlForOrval}/ok`;
};

/**
 * @summary Health endpoint, returns always OK
 */
export const health = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<healthResponse> => {
    const res = await (fetchFn ?? fetch)(getHealthUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: healthResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as healthResponse;
};

export const getHealthQueryKey = () => {
    return [`${apiUrlForOrval}/ok`] as const;
};

export const getHealthQueryOptions = <
    TData = Awaited<ReturnType<typeof health>>,
    TError = unknown
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getHealthQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof health>>> = ({ signal }) =>
        health({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof health>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthQueryResult = NonNullable<Awaited<ReturnType<typeof health>>>;
export type HealthQueryError = unknown;

/**
 * @summary Health endpoint, returns always OK
 */

export function createHealth<TData = Awaited<ReturnType<typeof health>>, TError = unknown>(
    options?: () => {
        query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof health>>, TError, TData>>;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getHealthQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}
