/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type {
    AlrightResponse,
    ApiError,
    AuditLog,
    ChangeEmailRequest,
    ChangeNameRequest,
    ExchangeChangeEmailRequest,
    User
} from "../model";

export type currentUserInfoResponse200 = {
    data: User;
    status: 200;
};

export type currentUserInfoResponse500 = {
    data: ApiError;
    status: 500;
};

export type currentUserInfoResponseSuccess = currentUserInfoResponse200 & {
    headers: Headers;
};
export type currentUserInfoResponseError = currentUserInfoResponse500 & {
    headers: Headers;
};

export type currentUserInfoResponse = currentUserInfoResponseSuccess | currentUserInfoResponseError;

export const getCurrentUserInfoUrl = () => {
    return `${apiUrlForOrval}/v1/me`;
};

/**
 * @summary Get your current user information
 */
export const currentUserInfo = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<currentUserInfoResponse> => {
    const res = await (fetchFn ?? fetch)(getCurrentUserInfoUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: currentUserInfoResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as currentUserInfoResponse;
};

export const getCurrentUserInfoQueryKey = () => {
    return [`${apiUrlForOrval}/v1/me`] as const;
};

export const getCurrentUserInfoQueryOptions = <
    TData = Awaited<ReturnType<typeof currentUserInfo>>,
    TError = ApiError
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof currentUserInfo>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getCurrentUserInfoQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof currentUserInfo>>> = ({ signal }) =>
        currentUserInfo({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof currentUserInfo>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CurrentUserInfoQueryResult = NonNullable<Awaited<ReturnType<typeof currentUserInfo>>>;
export type CurrentUserInfoQueryError = ApiError;

/**
 * @summary Get your current user information
 */

export function createCurrentUserInfo<
    TData = Awaited<ReturnType<typeof currentUserInfo>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof currentUserInfo>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getCurrentUserInfoQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type currentUserAuditLogResponse200 = {
    data: AuditLog;
    status: 200;
};

export type currentUserAuditLogResponse500 = {
    data: ApiError;
    status: 500;
};

export type currentUserAuditLogResponseSuccess = currentUserAuditLogResponse200 & {
    headers: Headers;
};
export type currentUserAuditLogResponseError = currentUserAuditLogResponse500 & {
    headers: Headers;
};

export type currentUserAuditLogResponse =
    | currentUserAuditLogResponseSuccess
    | currentUserAuditLogResponseError;

export const getCurrentUserAuditLogUrl = () => {
    return `${apiUrlForOrval}/v1/me/account/audit`;
};

/**
 * @summary Get your current user audit log
 */
export const currentUserAuditLog = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<currentUserAuditLogResponse> => {
    const res = await (fetchFn ?? fetch)(getCurrentUserAuditLogUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: currentUserAuditLogResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as currentUserAuditLogResponse;
};

export const getCurrentUserAuditLogQueryKey = () => {
    return [`${apiUrlForOrval}/v1/me/account/audit`] as const;
};

export const getCurrentUserAuditLogQueryOptions = <
    TData = Awaited<ReturnType<typeof currentUserAuditLog>>,
    TError = ApiError
>(options?: {
    query?: Partial<
        CreateQueryOptions<Awaited<ReturnType<typeof currentUserAuditLog>>, TError, TData>
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getCurrentUserAuditLogQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof currentUserAuditLog>>> = ({ signal }) =>
        currentUserAuditLog({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof currentUserAuditLog>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CurrentUserAuditLogQueryResult = NonNullable<
    Awaited<ReturnType<typeof currentUserAuditLog>>
>;
export type CurrentUserAuditLogQueryError = ApiError;

/**
 * @summary Get your current user audit log
 */

export function createCurrentUserAuditLog<
    TData = Awaited<ReturnType<typeof currentUserAuditLog>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof currentUserAuditLog>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getCurrentUserAuditLogQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type exchangeChangeUserEmailResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type exchangeChangeUserEmailResponse400 = {
    data: ApiError;
    status: 400;
};

export type exchangeChangeUserEmailResponse404 = {
    data: ApiError;
    status: 404;
};

export type exchangeChangeUserEmailResponse500 = {
    data: ApiError;
    status: 500;
};

export type exchangeChangeUserEmailResponseSuccess = exchangeChangeUserEmailResponse200 & {
    headers: Headers;
};
export type exchangeChangeUserEmailResponseError = (
    | exchangeChangeUserEmailResponse400
    | exchangeChangeUserEmailResponse404
    | exchangeChangeUserEmailResponse500
) & {
    headers: Headers;
};

export type exchangeChangeUserEmailResponse =
    | exchangeChangeUserEmailResponseSuccess
    | exchangeChangeUserEmailResponseError;

export const getExchangeChangeUserEmailUrl = () => {
    return `${apiUrlForOrval}/v1/me/account/email`;
};

/**
 * @summary Exchange the Email Change Token
 */
export const exchangeChangeUserEmail = async (
    exchangeChangeEmailRequest: ExchangeChangeEmailRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<exchangeChangeUserEmailResponse> => {
    const res = await (fetchFn ?? fetch)(getExchangeChangeUserEmailUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(exchangeChangeEmailRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: exchangeChangeUserEmailResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as exchangeChangeUserEmailResponse;
};

export const getExchangeChangeUserEmailMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof exchangeChangeUserEmail>>,
        TError,
        { data: ExchangeChangeEmailRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof exchangeChangeUserEmail>>,
    TError,
    { data: ExchangeChangeEmailRequest },
    TContext
> => {
    const mutationKey = ["exchangeChangeUserEmail"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof exchangeChangeUserEmail>>,
        { data: ExchangeChangeEmailRequest }
    > = (props) => {
        const { data } = props ?? {};

        return exchangeChangeUserEmail(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type ExchangeChangeUserEmailMutationResult = NonNullable<
    Awaited<ReturnType<typeof exchangeChangeUserEmail>>
>;
export type ExchangeChangeUserEmailMutationBody = ExchangeChangeEmailRequest;
export type ExchangeChangeUserEmailMutationError = ApiError;

/**
 * @summary Exchange the Email Change Token
 */
export const createExchangeChangeUserEmail = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof exchangeChangeUserEmail>>,
            TError,
            { data: ExchangeChangeEmailRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof exchangeChangeUserEmail>>,
    TError,
    { data: ExchangeChangeEmailRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getExchangeChangeUserEmailMutationOptions(options?.()) }),
        queryClient
    );
};
export type changeUserEmailResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type changeUserEmailResponse400 = {
    data: ApiError;
    status: 400;
};

export type changeUserEmailResponse401 = {
    data: ApiError;
    status: 401;
};

export type changeUserEmailResponse500 = {
    data: ApiError;
    status: 500;
};

export type changeUserEmailResponseSuccess = changeUserEmailResponse200 & {
    headers: Headers;
};
export type changeUserEmailResponseError = (
    | changeUserEmailResponse400
    | changeUserEmailResponse401
    | changeUserEmailResponse500
) & {
    headers: Headers;
};

export type changeUserEmailResponse = changeUserEmailResponseSuccess | changeUserEmailResponseError;

export const getChangeUserEmailUrl = () => {
    return `${apiUrlForOrval}/v1/me/account/email`;
};

/**
 * This will send a verification email to both your current and new email addresses. You must verify both emails to complete the change.
 * @summary Change your current email address
 */
export const changeUserEmail = async (
    changeEmailRequest: ChangeEmailRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<changeUserEmailResponse> => {
    const res = await (fetchFn ?? fetch)(getChangeUserEmailUrl(), {
        credentials: "include",
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(changeEmailRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: changeUserEmailResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as changeUserEmailResponse;
};

export const getChangeUserEmailMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof changeUserEmail>>,
        TError,
        { data: ChangeEmailRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof changeUserEmail>>,
    TError,
    { data: ChangeEmailRequest },
    TContext
> => {
    const mutationKey = ["changeUserEmail"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof changeUserEmail>>,
        { data: ChangeEmailRequest }
    > = (props) => {
        const { data } = props ?? {};

        return changeUserEmail(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type ChangeUserEmailMutationResult = NonNullable<
    Awaited<ReturnType<typeof changeUserEmail>>
>;
export type ChangeUserEmailMutationBody = ChangeEmailRequest;
export type ChangeUserEmailMutationError = ApiError;

/**
 * @summary Change your current email address
 */
export const createChangeUserEmail = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof changeUserEmail>>,
            TError,
            { data: ChangeEmailRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof changeUserEmail>>,
    TError,
    { data: ChangeEmailRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getChangeUserEmailMutationOptions(options?.()) }),
        queryClient
    );
};
export type changeUserNameResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type changeUserNameResponse403 = {
    data: ApiError;
    status: 403;
};

export type changeUserNameResponse500 = {
    data: ApiError;
    status: 500;
};

export type changeUserNameResponseSuccess = changeUserNameResponse200 & {
    headers: Headers;
};
export type changeUserNameResponseError = (
    | changeUserNameResponse403
    | changeUserNameResponse500
) & {
    headers: Headers;
};

export type changeUserNameResponse = changeUserNameResponseSuccess | changeUserNameResponseError;

export const getChangeUserNameUrl = () => {
    return `${apiUrlForOrval}/v1/me/account/login`;
};

/**
 * @summary Change your current name
 */
export const changeUserName = async (
    changeNameRequest: ChangeNameRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<changeUserNameResponse> => {
    const res = await (fetchFn ?? fetch)(getChangeUserNameUrl(), {
        credentials: "include",
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(changeNameRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: changeUserNameResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as changeUserNameResponse;
};

export const getChangeUserNameMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof changeUserName>>,
        TError,
        { data: ChangeNameRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof changeUserName>>,
    TError,
    { data: ChangeNameRequest },
    TContext
> => {
    const mutationKey = ["changeUserName"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof changeUserName>>,
        { data: ChangeNameRequest }
    > = (props) => {
        const { data } = props ?? {};

        return changeUserName(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type ChangeUserNameMutationResult = NonNullable<Awaited<ReturnType<typeof changeUserName>>>;
export type ChangeUserNameMutationBody = ChangeNameRequest;
export type ChangeUserNameMutationError = ApiError;

/**
 * @summary Change your current name
 */
export const createChangeUserName = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof changeUserName>>,
            TError,
            { data: ChangeNameRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof changeUserName>>,
    TError,
    { data: ChangeNameRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getChangeUserNameMutationOptions(options?.()) }),
        queryClient
    );
};
export type logoutResponse200 = {
    data: void;
    status: 200;
};

export type logoutResponse500 = {
    data: ApiError;
    status: 500;
};

export type logoutResponseSuccess = logoutResponse200 & {
    headers: Headers;
};
export type logoutResponseError = logoutResponse500 & {
    headers: Headers;
};

export type logoutResponse = logoutResponseSuccess | logoutResponseError;

export const getLogoutUrl = () => {
    return `${apiUrlForOrval}/v1/me/logout`;
};

/**
 * @summary Log out of this session
 */
export const logout = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<logoutResponse> => {
    const res = await (fetchFn ?? fetch)(getLogoutUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: logoutResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as logoutResponse;
};

export const getLogoutMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
    const mutationKey = ["logout"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
        return logout(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>;

export type LogoutMutationError = ApiError;

/**
 * @summary Log out of this session
 */
export const createLogout = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof logout>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
    return createMutation(() => ({ ...getLogoutMutationOptions(options?.()) }), queryClient);
};
