/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    MutationFunction,
    QueryClient
} from "@tanstack/svelte-query";

import type { ApiError, CreateTotpResponse, VerifyTotpRequest } from "../model";

export type createTotpOptionsResponse200 = {
    data: CreateTotpResponse;
    status: 200;
};

export type createTotpOptionsResponse400 = {
    data: ApiError;
    status: 400;
};

export type createTotpOptionsResponse401 = {
    data: ApiError;
    status: 401;
};

export type createTotpOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type createTotpOptionsResponseSuccess = createTotpOptionsResponse200 & {
    headers: Headers;
};
export type createTotpOptionsResponseError = (
    | createTotpOptionsResponse400
    | createTotpOptionsResponse401
    | createTotpOptionsResponse500
) & {
    headers: Headers;
};

export type createTotpOptionsResponse =
    | createTotpOptionsResponseSuccess
    | createTotpOptionsResponseError;

export const getCreateTotpOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp`;
};

/**
 * @summary Get the TOTP enrollment necessary data
 */
export const createTotpOptions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<createTotpOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getCreateTotpOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: createTotpOptionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as createTotpOptionsResponse;
};

export const getCreateTotpOptionsMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof createTotpOptions>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof createTotpOptions>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["createTotpOptions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createTotpOptions>>,
        void
    > = () => {
        return createTotpOptions(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateTotpOptionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof createTotpOptions>>
>;

export type CreateTotpOptionsMutationError = ApiError;

/**
 * @summary Get the TOTP enrollment necessary data
 */
export const createCreateTotpOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof createTotpOptions>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof createTotpOptions>>, TError, void, TContext> => {
    return createMutation(
        () => ({ ...getCreateTotpOptionsMutationOptions(options?.()) }),
        queryClient
    );
};
export type disableTotpResponse200 = {
    data: void;
    status: 200;
};

export type disableTotpResponse400 = {
    data: ApiError;
    status: 400;
};

export type disableTotpResponse401 = {
    data: ApiError;
    status: 401;
};

export type disableTotpResponse500 = {
    data: ApiError;
    status: 500;
};

export type disableTotpResponseSuccess = disableTotpResponse200 & {
    headers: Headers;
};
export type disableTotpResponseError = (
    | disableTotpResponse400
    | disableTotpResponse401
    | disableTotpResponse500
) & {
    headers: Headers;
};

export type disableTotpResponse = disableTotpResponseSuccess | disableTotpResponseError;

export const getDisableTotpUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp`;
};

/**
 * @summary Disable TOTP
 */
export const disableTotp = async (
    verifyTotpRequest: VerifyTotpRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<disableTotpResponse> => {
    const res = await (fetchFn ?? fetch)(getDisableTotpUrl(), {
        credentials: "include",
        ...options,
        method: "DELETE",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(verifyTotpRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: disableTotpResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as disableTotpResponse;
};

export const getDisableTotpMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof disableTotp>>,
        TError,
        { data: VerifyTotpRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof disableTotp>>,
    TError,
    { data: VerifyTotpRequest },
    TContext
> => {
    const mutationKey = ["disableTotp"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof disableTotp>>,
        { data: VerifyTotpRequest }
    > = (props) => {
        const { data } = props ?? {};

        return disableTotp(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type DisableTotpMutationResult = NonNullable<Awaited<ReturnType<typeof disableTotp>>>;
export type DisableTotpMutationBody = VerifyTotpRequest;
export type DisableTotpMutationError = ApiError;

/**
 * @summary Disable TOTP
 */
export const createDisableTotp = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof disableTotp>>,
            TError,
            { data: VerifyTotpRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof disableTotp>>,
    TError,
    { data: VerifyTotpRequest },
    TContext
> => {
    return createMutation(() => ({ ...getDisableTotpMutationOptions(options?.()) }), queryClient);
};
export type exchangeTotpCreationResponse200 = {
    data: void;
    status: 200;
};

export type exchangeTotpCreationResponse400 = {
    data: ApiError;
    status: 400;
};

export type exchangeTotpCreationResponse401 = {
    data: ApiError;
    status: 401;
};

export type exchangeTotpCreationResponse404 = {
    data: ApiError;
    status: 404;
};

export type exchangeTotpCreationResponse500 = {
    data: ApiError;
    status: 500;
};

export type exchangeTotpCreationResponseSuccess = exchangeTotpCreationResponse200 & {
    headers: Headers;
};
export type exchangeTotpCreationResponseError = (
    | exchangeTotpCreationResponse400
    | exchangeTotpCreationResponse401
    | exchangeTotpCreationResponse404
    | exchangeTotpCreationResponse500
) & {
    headers: Headers;
};

export type exchangeTotpCreationResponse =
    | exchangeTotpCreationResponseSuccess
    | exchangeTotpCreationResponseError;

export const getExchangeTotpCreationUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp/exchange`;
};

/**
 * This will enable TOTP for your account
 * @summary Exchange the TOTP enrollment with a generated code
 */
export const exchangeTotpCreation = async (
    verifyTotpRequest: VerifyTotpRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<exchangeTotpCreationResponse> => {
    const res = await (fetchFn ?? fetch)(getExchangeTotpCreationUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(verifyTotpRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: exchangeTotpCreationResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as exchangeTotpCreationResponse;
};

export const getExchangeTotpCreationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof exchangeTotpCreation>>,
        TError,
        { data: VerifyTotpRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof exchangeTotpCreation>>,
    TError,
    { data: VerifyTotpRequest },
    TContext
> => {
    const mutationKey = ["exchangeTotpCreation"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof exchangeTotpCreation>>,
        { data: VerifyTotpRequest }
    > = (props) => {
        const { data } = props ?? {};

        return exchangeTotpCreation(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type ExchangeTotpCreationMutationResult = NonNullable<
    Awaited<ReturnType<typeof exchangeTotpCreation>>
>;
export type ExchangeTotpCreationMutationBody = VerifyTotpRequest;
export type ExchangeTotpCreationMutationError = ApiError;

/**
 * @summary Exchange the TOTP enrollment with a generated code
 */
export const createExchangeTotpCreation = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof exchangeTotpCreation>>,
            TError,
            { data: VerifyTotpRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof exchangeTotpCreation>>,
    TError,
    { data: VerifyTotpRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getExchangeTotpCreationMutationOptions(options?.()) }),
        queryClient
    );
};
export type seeRecoveryCodesResponse200 = {
    data: void;
    status: 200;
};

export type seeRecoveryCodesResponse400 = {
    data: ApiError;
    status: 400;
};

export type seeRecoveryCodesResponse401 = {
    data: ApiError;
    status: 401;
};

export type seeRecoveryCodesResponse500 = {
    data: ApiError;
    status: 500;
};

export type seeRecoveryCodesResponseSuccess = seeRecoveryCodesResponse200 & {
    headers: Headers;
};
export type seeRecoveryCodesResponseError = (
    | seeRecoveryCodesResponse400
    | seeRecoveryCodesResponse401
    | seeRecoveryCodesResponse500
) & {
    headers: Headers;
};

export type seeRecoveryCodesResponse =
    | seeRecoveryCodesResponseSuccess
    | seeRecoveryCodesResponseError;

export const getSeeRecoveryCodesUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp/recovery`;
};

/**
 * @summary Get your TOTP recovery codes
 */
export const seeRecoveryCodes = async (
    verifyTotpRequest: VerifyTotpRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<seeRecoveryCodesResponse> => {
    const res = await (fetchFn ?? fetch)(getSeeRecoveryCodesUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(verifyTotpRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: seeRecoveryCodesResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as seeRecoveryCodesResponse;
};

export const getSeeRecoveryCodesMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof seeRecoveryCodes>>,
        TError,
        { data: VerifyTotpRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof seeRecoveryCodes>>,
    TError,
    { data: VerifyTotpRequest },
    TContext
> => {
    const mutationKey = ["seeRecoveryCodes"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof seeRecoveryCodes>>,
        { data: VerifyTotpRequest }
    > = (props) => {
        const { data } = props ?? {};

        return seeRecoveryCodes(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SeeRecoveryCodesMutationResult = NonNullable<
    Awaited<ReturnType<typeof seeRecoveryCodes>>
>;
export type SeeRecoveryCodesMutationBody = VerifyTotpRequest;
export type SeeRecoveryCodesMutationError = ApiError;

/**
 * @summary Get your TOTP recovery codes
 */
export const createSeeRecoveryCodes = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof seeRecoveryCodes>>,
            TError,
            { data: VerifyTotpRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof seeRecoveryCodes>>,
    TError,
    { data: VerifyTotpRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getSeeRecoveryCodesMutationOptions(options?.()) }),
        queryClient
    );
};
