/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    MutationFunction,
    QueryClient
} from "@tanstack/svelte-query";

import type {
    ApiError,
    CreateTotpResponse,
    RecoveryCodesTotpResponse,
    VerifyTotpRequest
} from "../model";

export type enableTotpOptionsResponse200 = {
    data: CreateTotpResponse;
    status: 200;
};

export type enableTotpOptionsResponse400 = {
    data: ApiError;
    status: 400;
};

export type enableTotpOptionsResponse401 = {
    data: ApiError;
    status: 401;
};

export type enableTotpOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type enableTotpOptionsResponseSuccess = enableTotpOptionsResponse200 & {
    headers: Headers;
};
export type enableTotpOptionsResponseError = (
    | enableTotpOptionsResponse400
    | enableTotpOptionsResponse401
    | enableTotpOptionsResponse500
) & {
    headers: Headers;
};

export type enableTotpOptionsResponse =
    | enableTotpOptionsResponseSuccess
    | enableTotpOptionsResponseError;

export const getEnableTotpOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp`;
};

/**
 * @summary Get the TOTP enrollment necessary data
 */
export const enableTotpOptions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<enableTotpOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getEnableTotpOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: enableTotpOptionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as enableTotpOptionsResponse;
};

export const getEnableTotpOptionsMutationKey = () => ["enableTotpOptions"] as const;

export const getEnableTotpOptionsMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof enableTotpOptions>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof enableTotpOptions>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = getEnableTotpOptionsMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof enableTotpOptions>>,
        void
    > = () => {
        return enableTotpOptions(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type EnableTotpOptionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof enableTotpOptions>>
>;

export type EnableTotpOptionsMutationError = ApiError;

/**
 * @summary Get the TOTP enrollment necessary data
 */
export const createEnableTotpOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof enableTotpOptions>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof enableTotpOptions>>, TError, void, TContext> => {
    return createMutation(
        () => ({ ...getEnableTotpOptionsMutationOptions(options?.()) }),
        queryClient
    );
};
export type disableTotpResponse200 = {
    data: void;
    status: 200;
};

export type disableTotpResponse400 = {
    data: ApiError;
    status: 400;
};

export type disableTotpResponse401 = {
    data: ApiError;
    status: 401;
};

export type disableTotpResponse500 = {
    data: ApiError;
    status: 500;
};

export type disableTotpResponseSuccess = disableTotpResponse200 & {
    headers: Headers;
};
export type disableTotpResponseError = (
    | disableTotpResponse400
    | disableTotpResponse401
    | disableTotpResponse500
) & {
    headers: Headers;
};

export type disableTotpResponse = disableTotpResponseSuccess | disableTotpResponseError;

export const getDisableTotpUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp`;
};

/**
 * @summary Disable TOTP
 */
export const disableTotp = async (
    verifyTotpRequest: VerifyTotpRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<disableTotpResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getDisableTotpUrl(), {
        credentials: "include",
        ...options,
        method: "DELETE",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(verifyTotpRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: disableTotpResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as disableTotpResponse;
};

export const getDisableTotpMutationKey = () => ["disableTotp"] as const;

export const getDisableTotpMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof disableTotp>>,
        TError,
        DisableTotpMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof disableTotp>>,
    TError,
    DisableTotpMutationVariables,
    TContext
> => {
    const mutationKey = getDisableTotpMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof disableTotp>>,
        DisableTotpMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return disableTotp(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type DisableTotpMutationResult = NonNullable<Awaited<ReturnType<typeof disableTotp>>>;
export type DisableTotpMutationBody = VerifyTotpRequest;
export type DisableTotpMutationError = ApiError;
export type DisableTotpMutationVariables = { data: VerifyTotpRequest };

/**
 * @summary Disable TOTP
 */
export const createDisableTotp = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof disableTotp>>,
            TError,
            DisableTotpMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof disableTotp>>,
    TError,
    DisableTotpMutationVariables,
    TContext
> => {
    return createMutation(() => ({ ...getDisableTotpMutationOptions(options?.()) }), queryClient);
};
export type exchangeTotpOptionsResponse200 = {
    data: void;
    status: 200;
};

export type exchangeTotpOptionsResponse400 = {
    data: ApiError;
    status: 400;
};

export type exchangeTotpOptionsResponse401 = {
    data: ApiError;
    status: 401;
};

export type exchangeTotpOptionsResponse404 = {
    data: ApiError;
    status: 404;
};

export type exchangeTotpOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type exchangeTotpOptionsResponseSuccess = exchangeTotpOptionsResponse200 & {
    headers: Headers;
};
export type exchangeTotpOptionsResponseError = (
    | exchangeTotpOptionsResponse400
    | exchangeTotpOptionsResponse401
    | exchangeTotpOptionsResponse404
    | exchangeTotpOptionsResponse500
) & {
    headers: Headers;
};

export type exchangeTotpOptionsResponse =
    | exchangeTotpOptionsResponseSuccess
    | exchangeTotpOptionsResponseError;

export const getExchangeTotpOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp/exchange`;
};

/**
 * This will enable TOTP for your account
 * @summary Exchange the TOTP enrollment with a generated code
 */
export const exchangeTotpOptions = async (
    verifyTotpRequest: VerifyTotpRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<exchangeTotpOptionsResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getExchangeTotpOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(verifyTotpRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: exchangeTotpOptionsResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as exchangeTotpOptionsResponse;
};

export const getExchangeTotpOptionsMutationKey = () => ["exchangeTotpOptions"] as const;

export const getExchangeTotpOptionsMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof exchangeTotpOptions>>,
        TError,
        ExchangeTotpOptionsMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof exchangeTotpOptions>>,
    TError,
    ExchangeTotpOptionsMutationVariables,
    TContext
> => {
    const mutationKey = getExchangeTotpOptionsMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof exchangeTotpOptions>>,
        ExchangeTotpOptionsMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return exchangeTotpOptions(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type ExchangeTotpOptionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof exchangeTotpOptions>>
>;
export type ExchangeTotpOptionsMutationBody = VerifyTotpRequest;
export type ExchangeTotpOptionsMutationError = ApiError;
export type ExchangeTotpOptionsMutationVariables = { data: VerifyTotpRequest };

/**
 * @summary Exchange the TOTP enrollment with a generated code
 */
export const createExchangeTotpOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof exchangeTotpOptions>>,
            TError,
            ExchangeTotpOptionsMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof exchangeTotpOptions>>,
    TError,
    ExchangeTotpOptionsMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getExchangeTotpOptionsMutationOptions(options?.()) }),
        queryClient
    );
};
export type viewTotpRecoveryCodesResponse200 = {
    data: RecoveryCodesTotpResponse;
    status: 200;
};

export type viewTotpRecoveryCodesResponse400 = {
    data: ApiError;
    status: 400;
};

export type viewTotpRecoveryCodesResponse401 = {
    data: ApiError;
    status: 401;
};

export type viewTotpRecoveryCodesResponse500 = {
    data: ApiError;
    status: 500;
};

export type viewTotpRecoveryCodesResponseSuccess = viewTotpRecoveryCodesResponse200 & {
    headers: Headers;
};
export type viewTotpRecoveryCodesResponseError = (
    | viewTotpRecoveryCodesResponse400
    | viewTotpRecoveryCodesResponse401
    | viewTotpRecoveryCodesResponse500
) & {
    headers: Headers;
};

export type viewTotpRecoveryCodesResponse =
    | viewTotpRecoveryCodesResponseSuccess
    | viewTotpRecoveryCodesResponseError;

export const getViewTotpRecoveryCodesUrl = () => {
    return `${apiUrlForOrval}/v1/me/totp/recovery`;
};

/**
 * @summary Get your TOTP recovery codes
 */
export const viewTotpRecoveryCodes = async (
    verifyTotpRequest: VerifyTotpRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<viewTotpRecoveryCodesResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getViewTotpRecoveryCodesUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(verifyTotpRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: viewTotpRecoveryCodesResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as viewTotpRecoveryCodesResponse;
};

export const getViewTotpRecoveryCodesMutationKey = () => ["viewTotpRecoveryCodes"] as const;

export const getViewTotpRecoveryCodesMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof viewTotpRecoveryCodes>>,
        TError,
        ViewTotpRecoveryCodesMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof viewTotpRecoveryCodes>>,
    TError,
    ViewTotpRecoveryCodesMutationVariables,
    TContext
> => {
    const mutationKey = getViewTotpRecoveryCodesMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof viewTotpRecoveryCodes>>,
        ViewTotpRecoveryCodesMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return viewTotpRecoveryCodes(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type ViewTotpRecoveryCodesMutationResult = NonNullable<
    Awaited<ReturnType<typeof viewTotpRecoveryCodes>>
>;
export type ViewTotpRecoveryCodesMutationBody = VerifyTotpRequest;
export type ViewTotpRecoveryCodesMutationError = ApiError;
export type ViewTotpRecoveryCodesMutationVariables = { data: VerifyTotpRequest };

/**
 * @summary Get your TOTP recovery codes
 */
export const createViewTotpRecoveryCodes = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof viewTotpRecoveryCodes>>,
            TError,
            ViewTotpRecoveryCodesMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof viewTotpRecoveryCodes>>,
    TError,
    ViewTotpRecoveryCodesMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getViewTotpRecoveryCodesMutationOptions(options?.()) }),
        queryClient
    );
};
