/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type {
    AlrightResponse,
    ApiError,
    AuthenticationPasskeyRequest,
    ExchangeRequest,
    FlowResponse,
    SudoOptionsResponse
} from "../model";

export type getEnableOptionsResponse200 = {
    data: SudoOptionsResponse;
    status: 200;
};

export type getEnableOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type getEnableOptionsResponseSuccess = getEnableOptionsResponse200 & {
    headers: Headers;
};
export type getEnableOptionsResponseError = getEnableOptionsResponse500 & {
    headers: Headers;
};

export type getEnableOptionsResponse =
    | getEnableOptionsResponseSuccess
    | getEnableOptionsResponseError;

export const getGetEnableOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo`;
};

/**
 * Requests what authentications methods you can use to re-authenticate with the current user.
 * @summary Get the Sudo Re-Authentication options
 */
export const getEnableOptions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<getEnableOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getGetEnableOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getEnableOptionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getEnableOptionsResponse;
};

export const getGetEnableOptionsQueryKey = () => {
    return [`${apiUrlForOrval}/v1/auth/sudo`] as const;
};

export const getGetEnableOptionsQueryOptions = <
    TData = Awaited<ReturnType<typeof getEnableOptions>>,
    TError = ApiError
>(options?: {
    query?: Partial<
        CreateQueryOptions<Awaited<ReturnType<typeof getEnableOptions>>, TError, TData>
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetEnableOptionsQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEnableOptions>>> = ({ signal }) =>
        getEnableOptions({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof getEnableOptions>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEnableOptionsQueryResult = NonNullable<Awaited<ReturnType<typeof getEnableOptions>>>;
export type GetEnableOptionsQueryError = ApiError;

/**
 * @summary Get the Sudo Re-Authentication options
 */

export function createGetEnableOptions<
    TData = Awaited<ReturnType<typeof getEnableOptions>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof getEnableOptions>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getGetEnableOptionsQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type sudoOtpExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type sudoOtpExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoOtpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type sudoOtpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoOtpExchangeResponseSuccess = sudoOtpExchangeResponse200 & {
    headers: Headers;
};
export type sudoOtpExchangeResponseError = (
    | sudoOtpExchangeResponse400
    | sudoOtpExchangeResponse401
    | sudoOtpExchangeResponse500
) & {
    headers: Headers;
};

export type sudoOtpExchangeResponse = sudoOtpExchangeResponseSuccess | sudoOtpExchangeResponseError;

export const getSudoOtpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/exchange`;
};

/**
 * @summary Exchange the Re-Authentication Flow ID made by an OTP code
 */
export const sudoOtpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoOtpExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoOtpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoOtpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoOtpExchangeResponse;
};

export const getSudoOtpExchangeMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoOtpExchange>>,
        TError,
        { data: ExchangeRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoOtpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    const mutationKey = ["sudoOtpExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoOtpExchange>>,
        { data: ExchangeRequest }
    > = (props) => {
        const { data } = props ?? {};

        return sudoOtpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoOtpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoOtpExchange>>
>;
export type SudoOtpExchangeMutationBody = ExchangeRequest;
export type SudoOtpExchangeMutationError = ApiError;

/**
 * @summary Exchange the Re-Authentication Flow ID made by an OTP code
 */
export const createSudoOtpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoOtpExchange>>,
            TError,
            { data: ExchangeRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof sudoOtpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getSudoOtpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type sudoTotpExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type sudoTotpExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoTotpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type sudoTotpExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type sudoTotpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoTotpExchangeResponseSuccess = sudoTotpExchangeResponse200 & {
    headers: Headers;
};
export type sudoTotpExchangeResponseError = (
    | sudoTotpExchangeResponse400
    | sudoTotpExchangeResponse401
    | sudoTotpExchangeResponse404
    | sudoTotpExchangeResponse500
) & {
    headers: Headers;
};

export type sudoTotpExchangeResponse =
    | sudoTotpExchangeResponseSuccess
    | sudoTotpExchangeResponseError;

export const getSudoTotpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/exchange/totp`;
};

/**
 * @summary Exchange the Re-Authentication Flow ID made by an enabled TOTP
 */
export const sudoTotpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoTotpExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoTotpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoTotpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoTotpExchangeResponse;
};

export const getSudoTotpExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoTotpExchange>>,
        TError,
        { data: ExchangeRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoTotpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    const mutationKey = ["sudoTotpExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoTotpExchange>>,
        { data: ExchangeRequest }
    > = (props) => {
        const { data } = props ?? {};

        return sudoTotpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoTotpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoTotpExchange>>
>;
export type SudoTotpExchangeMutationBody = ExchangeRequest;
export type SudoTotpExchangeMutationError = ApiError;

/**
 * @summary Exchange the Re-Authentication Flow ID made by an enabled TOTP
 */
export const createSudoTotpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoTotpExchange>>,
            TError,
            { data: ExchangeRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof sudoTotpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getSudoTotpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type sudoWebauthnExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type sudoWebauthnExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoWebauthnExchangeResponse403 = {
    data: ApiError;
    status: 403;
};

export type sudoWebauthnExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type sudoWebauthnExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoWebauthnExchangeResponseSuccess = sudoWebauthnExchangeResponse200 & {
    headers: Headers;
};
export type sudoWebauthnExchangeResponseError = (
    | sudoWebauthnExchangeResponse400
    | sudoWebauthnExchangeResponse403
    | sudoWebauthnExchangeResponse404
    | sudoWebauthnExchangeResponse500
) & {
    headers: Headers;
};

export type sudoWebauthnExchangeResponse =
    | sudoWebauthnExchangeResponseSuccess
    | sudoWebauthnExchangeResponseError;

export const getSudoWebauthnExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/exchange/webauthn`;
};

/**
 * @summary Exchange the Re-Authentication Flow made by a Passkey browser challenge
 */
export const sudoWebauthnExchange = async (
    authenticationPasskeyRequest: AuthenticationPasskeyRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoWebauthnExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoWebauthnExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(authenticationPasskeyRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoWebauthnExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoWebauthnExchangeResponse;
};

export const getSudoWebauthnExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoWebauthnExchange>>,
        TError,
        { data: AuthenticationPasskeyRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoWebauthnExchange>>,
    TError,
    { data: AuthenticationPasskeyRequest },
    TContext
> => {
    const mutationKey = ["sudoWebauthnExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoWebauthnExchange>>,
        { data: AuthenticationPasskeyRequest }
    > = (props) => {
        const { data } = props ?? {};

        return sudoWebauthnExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoWebauthnExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoWebauthnExchange>>
>;
export type SudoWebauthnExchangeMutationBody = AuthenticationPasskeyRequest;
export type SudoWebauthnExchangeMutationError = ApiError;

/**
 * @summary Exchange the Re-Authentication Flow made by a Passkey browser challenge
 */
export const createSudoWebauthnExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoWebauthnExchange>>,
            TError,
            { data: AuthenticationPasskeyRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof sudoWebauthnExchange>>,
    TError,
    { data: AuthenticationPasskeyRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getSudoWebauthnExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type otpOptionResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type otpOptionResponse400 = {
    data: ApiError;
    status: 400;
};

export type otpOptionResponse500 = {
    data: ApiError;
    status: 500;
};

export type otpOptionResponseSuccess = otpOptionResponse200 & {
    headers: Headers;
};
export type otpOptionResponseError = (otpOptionResponse400 | otpOptionResponse500) & {
    headers: Headers;
};

export type otpOptionResponse = otpOptionResponseSuccess | otpOptionResponseError;

export const getOtpOptionUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/start`;
};

/**
 * @summary Re-Authenticate via an OTP code
 */
export const otpOption = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<otpOptionResponse> => {
    const res = await (fetchFn ?? fetch)(getOtpOptionUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: otpOptionResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as otpOptionResponse;
};

export const getOtpOptionMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<Awaited<ReturnType<typeof otpOption>>, TError, void, TContext>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<Awaited<ReturnType<typeof otpOption>>, TError, void, TContext> => {
    const mutationKey = ["otpOption"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof otpOption>>, void> = () => {
        return otpOption(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type OtpOptionMutationResult = NonNullable<Awaited<ReturnType<typeof otpOption>>>;

export type OtpOptionMutationError = ApiError;

/**
 * @summary Re-Authenticate via an OTP code
 */
export const createOtpOption = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof otpOption>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof otpOption>>, TError, void, TContext> => {
    return createMutation(() => ({ ...getOtpOptionMutationOptions(options?.()) }), queryClient);
};
export type totpOptionResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type totpOptionResponse400 = {
    data: ApiError;
    status: 400;
};

export type totpOptionResponse500 = {
    data: ApiError;
    status: 500;
};

export type totpOptionResponseSuccess = totpOptionResponse200 & {
    headers: Headers;
};
export type totpOptionResponseError = (totpOptionResponse400 | totpOptionResponse500) & {
    headers: Headers;
};

export type totpOptionResponse = totpOptionResponseSuccess | totpOptionResponseError;

export const getTotpOptionUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/start/totp`;
};

/**
 * @summary Re-Authenticate via a TOTP code (if enabled)
 */
export const totpOption = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<totpOptionResponse> => {
    const res = await (fetchFn ?? fetch)(getTotpOptionUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: totpOptionResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as totpOptionResponse;
};

export const getTotpOptionMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof totpOption>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<Awaited<ReturnType<typeof totpOption>>, TError, void, TContext> => {
    const mutationKey = ["totpOption"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof totpOption>>, void> = () => {
        return totpOption(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type TotpOptionMutationResult = NonNullable<Awaited<ReturnType<typeof totpOption>>>;

export type TotpOptionMutationError = ApiError;

/**
 * @summary Re-Authenticate via a TOTP code (if enabled)
 */
export const createTotpOption = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof totpOption>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof totpOption>>, TError, void, TContext> => {
    return createMutation(() => ({ ...getTotpOptionMutationOptions(options?.()) }), queryClient);
};
export type webauthnOptionsResponse200 = {
    data: void;
    status: 200;
};

export type webauthnOptionsResponse400 = {
    data: ApiError;
    status: 400;
};

export type webauthnOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type webauthnOptionsResponseSuccess = webauthnOptionsResponse200 & {
    headers: Headers;
};
export type webauthnOptionsResponseError = (
    | webauthnOptionsResponse400
    | webauthnOptionsResponse500
) & {
    headers: Headers;
};

export type webauthnOptionsResponse = webauthnOptionsResponseSuccess | webauthnOptionsResponseError;

export const getWebauthnOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/start/webauthn`;
};

/**
 * Returns the challenge for the user's browser to use to re-authenticate.
 * @summary Re-Authenticate via a Passkey
 */
export const webauthnOptions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<webauthnOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getWebauthnOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: webauthnOptionsResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as webauthnOptionsResponse;
};

export const getWebauthnOptionsMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof webauthnOptions>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<Awaited<ReturnType<typeof webauthnOptions>>, TError, void, TContext> => {
    const mutationKey = ["webauthnOptions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof webauthnOptions>>, void> = () => {
        return webauthnOptions(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type WebauthnOptionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof webauthnOptions>>
>;

export type WebauthnOptionsMutationError = ApiError;

/**
 * @summary Re-Authenticate via a Passkey
 */
export const createWebauthnOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof webauthnOptions>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof webauthnOptions>>, TError, void, TContext> => {
    return createMutation(
        () => ({ ...getWebauthnOptionsMutationOptions(options?.()) }),
        queryClient
    );
};
