/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type {
    AlrightResponse,
    ApiError,
    AuthenticationPasskeyRequest,
    ExchangeRequest,
    FlowResponse,
    StartChallengeResponse,
    SudoOptionsResponse
} from "../model";

export type sudoEnableOptionsResponse200 = {
    data: SudoOptionsResponse;
    status: 200;
};

export type sudoEnableOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoEnableOptionsResponseSuccess = sudoEnableOptionsResponse200 & {
    headers: Headers;
};
export type sudoEnableOptionsResponseError = sudoEnableOptionsResponse500 & {
    headers: Headers;
};

export type sudoEnableOptionsResponse =
    | sudoEnableOptionsResponseSuccess
    | sudoEnableOptionsResponseError;

export const getSudoEnableOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo`;
};

/**
 * Requests what authentications methods you can use to re-authenticate with the current user.
 * @summary Get the Sudo Re-Authentication options
 */
export const sudoEnableOptions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoEnableOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoEnableOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoEnableOptionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoEnableOptionsResponse;
};

export const getSudoEnableOptionsQueryKey = () => {
    return ["sudoEnableOptions"] as const;
};

export const getSudoEnableOptionsQueryOptions = <
    TData = Awaited<ReturnType<typeof sudoEnableOptions>>,
    TError = ApiError
>(options?: {
    query?: Partial<
        CreateQueryOptions<Awaited<ReturnType<typeof sudoEnableOptions>>, TError, TData>
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSudoEnableOptionsQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sudoEnableOptions>>> = ({ signal }) =>
        sudoEnableOptions({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof sudoEnableOptions>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SudoEnableOptionsQueryResult = NonNullable<
    Awaited<ReturnType<typeof sudoEnableOptions>>
>;
export type SudoEnableOptionsQueryError = ApiError;

/**
 * @summary Get the Sudo Re-Authentication options
 */

export function createSudoEnableOptions<
    TData = Awaited<ReturnType<typeof sudoEnableOptions>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof sudoEnableOptions>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getSudoEnableOptionsQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type sudoOtpExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type sudoOtpExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoOtpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type sudoOtpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoOtpExchangeResponseSuccess = sudoOtpExchangeResponse200 & {
    headers: Headers;
};
export type sudoOtpExchangeResponseError = (
    | sudoOtpExchangeResponse400
    | sudoOtpExchangeResponse401
    | sudoOtpExchangeResponse500
) & {
    headers: Headers;
};

export type sudoOtpExchangeResponse = sudoOtpExchangeResponseSuccess | sudoOtpExchangeResponseError;

export const getSudoOtpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/exchange`;
};

/**
 * @summary Exchange the Re-Authentication Flow ID made by an OTP code
 */
export const sudoOtpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoOtpExchangeResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getSudoOtpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoOtpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoOtpExchangeResponse;
};

export const getSudoOtpExchangeMutationKey = () => ["sudoOtpExchange"] as const;

export const getSudoOtpExchangeMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoOtpExchange>>,
        TError,
        SudoOtpExchangeMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoOtpExchange>>,
    TError,
    SudoOtpExchangeMutationVariables,
    TContext
> => {
    const mutationKey = getSudoOtpExchangeMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoOtpExchange>>,
        SudoOtpExchangeMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return sudoOtpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoOtpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoOtpExchange>>
>;
export type SudoOtpExchangeMutationBody = ExchangeRequest;
export type SudoOtpExchangeMutationError = ApiError;
export type SudoOtpExchangeMutationVariables = { data: ExchangeRequest };

/**
 * @summary Exchange the Re-Authentication Flow ID made by an OTP code
 */
export const createSudoOtpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoOtpExchange>>,
            TError,
            SudoOtpExchangeMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof sudoOtpExchange>>,
    TError,
    SudoOtpExchangeMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getSudoOtpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type sudoTotpExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type sudoTotpExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoTotpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type sudoTotpExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type sudoTotpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoTotpExchangeResponseSuccess = sudoTotpExchangeResponse200 & {
    headers: Headers;
};
export type sudoTotpExchangeResponseError = (
    | sudoTotpExchangeResponse400
    | sudoTotpExchangeResponse401
    | sudoTotpExchangeResponse404
    | sudoTotpExchangeResponse500
) & {
    headers: Headers;
};

export type sudoTotpExchangeResponse =
    | sudoTotpExchangeResponseSuccess
    | sudoTotpExchangeResponseError;

export const getSudoTotpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/exchange/totp`;
};

/**
 * @summary Exchange the Re-Authentication Flow ID made by an enabled TOTP
 */
export const sudoTotpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoTotpExchangeResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getSudoTotpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoTotpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoTotpExchangeResponse;
};

export const getSudoTotpExchangeMutationKey = () => ["sudoTotpExchange"] as const;

export const getSudoTotpExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoTotpExchange>>,
        TError,
        SudoTotpExchangeMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoTotpExchange>>,
    TError,
    SudoTotpExchangeMutationVariables,
    TContext
> => {
    const mutationKey = getSudoTotpExchangeMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoTotpExchange>>,
        SudoTotpExchangeMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return sudoTotpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoTotpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoTotpExchange>>
>;
export type SudoTotpExchangeMutationBody = ExchangeRequest;
export type SudoTotpExchangeMutationError = ApiError;
export type SudoTotpExchangeMutationVariables = { data: ExchangeRequest };

/**
 * @summary Exchange the Re-Authentication Flow ID made by an enabled TOTP
 */
export const createSudoTotpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoTotpExchange>>,
            TError,
            SudoTotpExchangeMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof sudoTotpExchange>>,
    TError,
    SudoTotpExchangeMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getSudoTotpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type sudoWebauthnExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type sudoWebauthnExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoWebauthnExchangeResponse403 = {
    data: ApiError;
    status: 403;
};

export type sudoWebauthnExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type sudoWebauthnExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoWebauthnExchangeResponseSuccess = sudoWebauthnExchangeResponse200 & {
    headers: Headers;
};
export type sudoWebauthnExchangeResponseError = (
    | sudoWebauthnExchangeResponse400
    | sudoWebauthnExchangeResponse403
    | sudoWebauthnExchangeResponse404
    | sudoWebauthnExchangeResponse500
) & {
    headers: Headers;
};

export type sudoWebauthnExchangeResponse =
    | sudoWebauthnExchangeResponseSuccess
    | sudoWebauthnExchangeResponseError;

export const getSudoWebauthnExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/exchange/webauthn`;
};

/**
 * @summary Exchange the Re-Authentication Flow made by a Passkey browser challenge
 */
export const sudoWebauthnExchange = async (
    authenticationPasskeyRequest: AuthenticationPasskeyRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoWebauthnExchangeResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getSudoWebauthnExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(authenticationPasskeyRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoWebauthnExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoWebauthnExchangeResponse;
};

export const getSudoWebauthnExchangeMutationKey = () => ["sudoWebauthnExchange"] as const;

export const getSudoWebauthnExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoWebauthnExchange>>,
        TError,
        SudoWebauthnExchangeMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoWebauthnExchange>>,
    TError,
    SudoWebauthnExchangeMutationVariables,
    TContext
> => {
    const mutationKey = getSudoWebauthnExchangeMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoWebauthnExchange>>,
        SudoWebauthnExchangeMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return sudoWebauthnExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoWebauthnExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoWebauthnExchange>>
>;
export type SudoWebauthnExchangeMutationBody = AuthenticationPasskeyRequest;
export type SudoWebauthnExchangeMutationError = ApiError;
export type SudoWebauthnExchangeMutationVariables = { data: AuthenticationPasskeyRequest };

/**
 * @summary Exchange the Re-Authentication Flow made by a Passkey browser challenge
 */
export const createSudoWebauthnExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoWebauthnExchange>>,
            TError,
            SudoWebauthnExchangeMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof sudoWebauthnExchange>>,
    TError,
    SudoWebauthnExchangeMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getSudoWebauthnExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type sudoOtpStartResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type sudoOtpStartResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoOtpStartResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoOtpStartResponseSuccess = sudoOtpStartResponse200 & {
    headers: Headers;
};
export type sudoOtpStartResponseError = (sudoOtpStartResponse400 | sudoOtpStartResponse500) & {
    headers: Headers;
};

export type sudoOtpStartResponse = sudoOtpStartResponseSuccess | sudoOtpStartResponseError;

export const getSudoOtpStartUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/start`;
};

/**
 * @summary Re-Authenticate via an OTP code
 */
export const sudoOtpStart = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoOtpStartResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoOtpStartUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoOtpStartResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoOtpStartResponse;
};

export const getSudoOtpStartMutationKey = () => ["sudoOtpStart"] as const;

export const getSudoOtpStartMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoOtpStart>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<Awaited<ReturnType<typeof sudoOtpStart>>, TError, void, TContext> => {
    const mutationKey = getSudoOtpStartMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof sudoOtpStart>>, void> = () => {
        return sudoOtpStart(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoOtpStartMutationResult = NonNullable<Awaited<ReturnType<typeof sudoOtpStart>>>;

export type SudoOtpStartMutationError = ApiError;

/**
 * @summary Re-Authenticate via an OTP code
 */
export const createSudoOtpStart = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoOtpStart>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof sudoOtpStart>>, TError, void, TContext> => {
    return createMutation(() => ({ ...getSudoOtpStartMutationOptions(options?.()) }), queryClient);
};
export type sudoTotpStartResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type sudoTotpStartResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoTotpStartResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoTotpStartResponseSuccess = sudoTotpStartResponse200 & {
    headers: Headers;
};
export type sudoTotpStartResponseError = (sudoTotpStartResponse400 | sudoTotpStartResponse500) & {
    headers: Headers;
};

export type sudoTotpStartResponse = sudoTotpStartResponseSuccess | sudoTotpStartResponseError;

export const getSudoTotpStartUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/start/totp`;
};

/**
 * @summary Re-Authenticate via a TOTP code (if enabled)
 */
export const sudoTotpStart = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoTotpStartResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoTotpStartUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoTotpStartResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoTotpStartResponse;
};

export const getSudoTotpStartMutationKey = () => ["sudoTotpStart"] as const;

export const getSudoTotpStartMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoTotpStart>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<Awaited<ReturnType<typeof sudoTotpStart>>, TError, void, TContext> => {
    const mutationKey = getSudoTotpStartMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof sudoTotpStart>>, void> = () => {
        return sudoTotpStart(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoTotpStartMutationResult = NonNullable<Awaited<ReturnType<typeof sudoTotpStart>>>;

export type SudoTotpStartMutationError = ApiError;

/**
 * @summary Re-Authenticate via a TOTP code (if enabled)
 */
export const createSudoTotpStart = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoTotpStart>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof sudoTotpStart>>, TError, void, TContext> => {
    return createMutation(() => ({ ...getSudoTotpStartMutationOptions(options?.()) }), queryClient);
};
export type sudoWebauthnStartResponse200 = {
    data: StartChallengeResponse;
    status: 200;
};

export type sudoWebauthnStartResponse400 = {
    data: ApiError;
    status: 400;
};

export type sudoWebauthnStartResponse500 = {
    data: ApiError;
    status: 500;
};

export type sudoWebauthnStartResponseSuccess = sudoWebauthnStartResponse200 & {
    headers: Headers;
};
export type sudoWebauthnStartResponseError = (
    | sudoWebauthnStartResponse400
    | sudoWebauthnStartResponse500
) & {
    headers: Headers;
};

export type sudoWebauthnStartResponse =
    | sudoWebauthnStartResponseSuccess
    | sudoWebauthnStartResponseError;

export const getSudoWebauthnStartUrl = () => {
    return `${apiUrlForOrval}/v1/auth/sudo/start/webauthn`;
};

/**
 * Returns the challenge for the user's browser to use to re-authenticate.
 * @summary Re-Authenticate via a Passkey
 */
export const sudoWebauthnStart = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<sudoWebauthnStartResponse> => {
    const res = await (fetchFn ?? fetch)(getSudoWebauthnStartUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: sudoWebauthnStartResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as sudoWebauthnStartResponse;
};

export const getSudoWebauthnStartMutationKey = () => ["sudoWebauthnStart"] as const;

export const getSudoWebauthnStartMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof sudoWebauthnStart>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof sudoWebauthnStart>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = getSudoWebauthnStartMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof sudoWebauthnStart>>,
        void
    > = () => {
        return sudoWebauthnStart(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type SudoWebauthnStartMutationResult = NonNullable<
    Awaited<ReturnType<typeof sudoWebauthnStart>>
>;

export type SudoWebauthnStartMutationError = ApiError;

/**
 * @summary Re-Authenticate via a Passkey
 */
export const createSudoWebauthnStart = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof sudoWebauthnStart>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof sudoWebauthnStart>>, TError, void, TContext> => {
    return createMutation(
        () => ({ ...getSudoWebauthnStartMutationOptions(options?.()) }),
        queryClient
    );
};
