/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type {
    ApiError,
    AuthorizationDecisionRequest,
    AuthorizationRequest,
    ConsentMetadata,
    JwkKeySet,
    OauthMetadata,
    OpenIdMetadata,
    OpenIdUserInfo,
    TokenRequest,
    TokenResponse
} from "../model";

export type wellknownOauthResponse200 = {
    data: OauthMetadata;
    status: 200;
};

export type wellknownOauthResponseSuccess = wellknownOauthResponse200 & {
    headers: Headers;
};

export type wellknownOauthResponse = wellknownOauthResponseSuccess;

export const getWellknownOauthUrl = () => {
    return `${apiUrlForOrval}/.well-known/oauth-authorization-server`;
};

/**
 * @summary Get the oauth server's metadata
 */
export const wellknownOauth = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<wellknownOauthResponse> => {
    const res = await (fetchFn ?? fetch)(getWellknownOauthUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: wellknownOauthResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as wellknownOauthResponse;
};

export const getWellknownOauthQueryKey = () => {
    return [`${apiUrlForOrval}/.well-known/oauth-authorization-server`] as const;
};

export const getWellknownOauthQueryOptions = <
    TData = Awaited<ReturnType<typeof wellknownOauth>>,
    TError = unknown
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof wellknownOauth>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getWellknownOauthQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof wellknownOauth>>> = ({ signal }) =>
        wellknownOauth({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof wellknownOauth>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WellknownOauthQueryResult = NonNullable<Awaited<ReturnType<typeof wellknownOauth>>>;
export type WellknownOauthQueryError = unknown;

/**
 * @summary Get the oauth server's metadata
 */

export function createWellknownOauth<
    TData = Awaited<ReturnType<typeof wellknownOauth>>,
    TError = unknown
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof wellknownOauth>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getWellknownOauthQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type wellknownOpenidResponse200 = {
    data: OpenIdMetadata;
    status: 200;
};

export type wellknownOpenidResponseSuccess = wellknownOpenidResponse200 & {
    headers: Headers;
};

export type wellknownOpenidResponse = wellknownOpenidResponseSuccess;

export const getWellknownOpenidUrl = () => {
    return `${apiUrlForOrval}/.well-known/openid-configuration`;
};

/**
 * @summary Get the openid server's metadata
 */
export const wellknownOpenid = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<wellknownOpenidResponse> => {
    const res = await (fetchFn ?? fetch)(getWellknownOpenidUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: wellknownOpenidResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as wellknownOpenidResponse;
};

export const getWellknownOpenidQueryKey = () => {
    return [`${apiUrlForOrval}/.well-known/openid-configuration`] as const;
};

export const getWellknownOpenidQueryOptions = <
    TData = Awaited<ReturnType<typeof wellknownOpenid>>,
    TError = unknown
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof wellknownOpenid>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getWellknownOpenidQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof wellknownOpenid>>> = ({ signal }) =>
        wellknownOpenid({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof wellknownOpenid>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WellknownOpenidQueryResult = NonNullable<Awaited<ReturnType<typeof wellknownOpenid>>>;
export type WellknownOpenidQueryError = unknown;

/**
 * @summary Get the openid server's metadata
 */

export function createWellknownOpenid<
    TData = Awaited<ReturnType<typeof wellknownOpenid>>,
    TError = unknown
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof wellknownOpenid>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getWellknownOpenidQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type authorizeResponse303 = {
    data: void;
    status: 303;
};

export type authorizeResponse500 = {
    data: ApiError;
    status: 500;
};
export type authorizeResponseError = (authorizeResponse303 | authorizeResponse500) & {
    headers: Headers;
};

export type authorizeResponse = authorizeResponseError;

export const getAuthorizeUrl = () => {
    return `${apiUrlForOrval}/v1/oauth2/authorize`;
};

/**
 * This endpoint is used to authorize an oauth application.
 * It will redirect to the consent screen if the current user has not authorized this application
 * else it will redirect to the application's redirect_uri with typical oauth stuff.
 * @summary Authorize an oauth application.
 */
export const authorize = async (
    authorizationRequest: AuthorizationRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<authorizeResponse> => {
    const formUrlEncoded = new URLSearchParams();
    formUrlEncoded.append(`client_id`, authorizationRequest.client_id);
    formUrlEncoded.append(`code_challenge`, authorizationRequest.code_challenge);
    formUrlEncoded.append(`code_challenge_method`, authorizationRequest.code_challenge_method);
    if (authorizationRequest.nonce !== undefined && authorizationRequest.nonce !== null) {
        formUrlEncoded.append(`nonce`, authorizationRequest.nonce);
    }
    if (authorizationRequest.prompt !== undefined && authorizationRequest.prompt !== null) {
        formUrlEncoded.append(`prompt`, authorizationRequest.prompt);
    }
    if (
        authorizationRequest.redirect_uri !== undefined &&
        authorizationRequest.redirect_uri !== null
    ) {
        formUrlEncoded.append(`redirect_uri`, authorizationRequest.redirect_uri);
    }
    formUrlEncoded.append(`response_type`, authorizationRequest.response_type);
    if (authorizationRequest.scope !== undefined && authorizationRequest.scope !== null) {
        formUrlEncoded.append(`scope`, authorizationRequest.scope);
    }
    if (authorizationRequest.state !== undefined && authorizationRequest.state !== null) {
        formUrlEncoded.append(`state`, authorizationRequest.state);
    }

    const res = await (fetchFn ?? fetch)(getAuthorizeUrl(), {
        credentials: "include",
        ...options,
        method: "GET",
        headers: { "Content-Type": "application/x-www-form-urlencoded", ...options?.headers },
        body: formUrlEncoded
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: authorizeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as authorizeResponse;
};

export const getAuthorizeQueryKey = (authorizationRequest?: AuthorizationRequest) => {
    return [`${apiUrlForOrval}/v1/oauth2/authorize`, authorizationRequest] as const;
};

export const getAuthorizeQueryOptions = <
    TData = Awaited<ReturnType<typeof authorize>>,
    TError = void | ApiError
>(
    authorizationRequest: AuthorizationRequest,
    options?: {
        query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof authorize>>, TError, TData>>;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getAuthorizeQueryKey(authorizationRequest);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authorize>>> = ({ signal }) =>
        authorize(authorizationRequest, { signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof authorize>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthorizeQueryResult = NonNullable<Awaited<ReturnType<typeof authorize>>>;
export type AuthorizeQueryError = void | ApiError;

/**
 * @summary Authorize an oauth application.
 */

export function createAuthorize<
    TData = Awaited<ReturnType<typeof authorize>>,
    TError = void | ApiError
>(
    authorizationRequest: () => AuthorizationRequest,
    options?: () => {
        query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof authorize>>, TError, TData>>;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getAuthorizeQueryOptions(authorizationRequest(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type oauthConsentInfoResponse200 = {
    data: ConsentMetadata;
    status: 200;
};

export type oauthConsentInfoResponse500 = {
    data: ApiError;
    status: 500;
};

export type oauthConsentInfoResponseSuccess = oauthConsentInfoResponse200 & {
    headers: Headers;
};
export type oauthConsentInfoResponseError = oauthConsentInfoResponse500 & {
    headers: Headers;
};

export type oauthConsentInfoResponse =
    | oauthConsentInfoResponseSuccess
    | oauthConsentInfoResponseError;

export const getOauthConsentInfoUrl = () => {
    return `${apiUrlForOrval}/v1/oauth2/consent`;
};

/**
 * @summary Get the pending oauth authorization metadata
 */
export const oauthConsentInfo = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<oauthConsentInfoResponse> => {
    const res = await (fetchFn ?? fetch)(getOauthConsentInfoUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: oauthConsentInfoResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as oauthConsentInfoResponse;
};

export const getOauthConsentInfoQueryKey = () => {
    return [`${apiUrlForOrval}/v1/oauth2/consent`] as const;
};

export const getOauthConsentInfoQueryOptions = <
    TData = Awaited<ReturnType<typeof oauthConsentInfo>>,
    TError = ApiError
>(options?: {
    query?: Partial<
        CreateQueryOptions<Awaited<ReturnType<typeof oauthConsentInfo>>, TError, TData>
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getOauthConsentInfoQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof oauthConsentInfo>>> = ({ signal }) =>
        oauthConsentInfo({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof oauthConsentInfo>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OauthConsentInfoQueryResult = NonNullable<Awaited<ReturnType<typeof oauthConsentInfo>>>;
export type OauthConsentInfoQueryError = ApiError;

/**
 * @summary Get the pending oauth authorization metadata
 */

export function createOauthConsentInfo<
    TData = Awaited<ReturnType<typeof oauthConsentInfo>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof oauthConsentInfo>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getOauthConsentInfoQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type finishAuthorizationResponse200 = {
    data: void;
    status: 200;
};

export type finishAuthorizationResponse303 = {
    data: void;
    status: 303;
};

export type finishAuthorizationResponse500 = {
    data: ApiError;
    status: 500;
};

export type finishAuthorizationResponseSuccess = finishAuthorizationResponse200 & {
    headers: Headers;
};
export type finishAuthorizationResponseError = (
    | finishAuthorizationResponse303
    | finishAuthorizationResponse500
) & {
    headers: Headers;
};

export type finishAuthorizationResponse =
    | finishAuthorizationResponseSuccess
    | finishAuthorizationResponseError;

export const getFinishAuthorizationUrl = () => {
    return `${apiUrlForOrval}/v1/oauth2/consent`;
};

/**
 * @summary Give consent to a pending oauth authorization.
 */
export const finishAuthorization = async (
    authorizationDecisionRequest: AuthorizationDecisionRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<finishAuthorizationResponse> => {
    const res = await (fetchFn ?? fetch)(getFinishAuthorizationUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(authorizationDecisionRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: finishAuthorizationResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as finishAuthorizationResponse;
};

export const getFinishAuthorizationMutationOptions = <
    TError = void | ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof finishAuthorization>>,
        TError,
        { data: AuthorizationDecisionRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof finishAuthorization>>,
    TError,
    { data: AuthorizationDecisionRequest },
    TContext
> => {
    const mutationKey = ["finishAuthorization"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof finishAuthorization>>,
        { data: AuthorizationDecisionRequest }
    > = (props) => {
        const { data } = props ?? {};

        return finishAuthorization(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FinishAuthorizationMutationResult = NonNullable<
    Awaited<ReturnType<typeof finishAuthorization>>
>;
export type FinishAuthorizationMutationBody = AuthorizationDecisionRequest;
export type FinishAuthorizationMutationError = void | ApiError;

/**
 * @summary Give consent to a pending oauth authorization.
 */
export const createFinishAuthorization = <TError = void | ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof finishAuthorization>>,
            TError,
            { data: AuthorizationDecisionRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof finishAuthorization>>,
    TError,
    { data: AuthorizationDecisionRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getFinishAuthorizationMutationOptions(options?.()) }),
        queryClient
    );
};
export type oauthDiscoveryJwksResponse200 = {
    data: JwkKeySet;
    status: 200;
};

export type oauthDiscoveryJwksResponseSuccess = oauthDiscoveryJwksResponse200 & {
    headers: Headers;
};

export type oauthDiscoveryJwksResponse = oauthDiscoveryJwksResponseSuccess;

export const getOauthDiscoveryJwksUrl = () => {
    return `${apiUrlForOrval}/v1/oauth2/discovery/keys`;
};

/**
 * @summary Get the oauth server's public keys (JWKs)
 */
export const oauthDiscoveryJwks = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<oauthDiscoveryJwksResponse> => {
    const res = await (fetchFn ?? fetch)(getOauthDiscoveryJwksUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: oauthDiscoveryJwksResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as oauthDiscoveryJwksResponse;
};

export const getOauthDiscoveryJwksQueryKey = () => {
    return [`${apiUrlForOrval}/v1/oauth2/discovery/keys`] as const;
};

export const getOauthDiscoveryJwksQueryOptions = <
    TData = Awaited<ReturnType<typeof oauthDiscoveryJwks>>,
    TError = unknown
>(options?: {
    query?: Partial<
        CreateQueryOptions<Awaited<ReturnType<typeof oauthDiscoveryJwks>>, TError, TData>
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getOauthDiscoveryJwksQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof oauthDiscoveryJwks>>> = ({ signal }) =>
        oauthDiscoveryJwks({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof oauthDiscoveryJwks>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OauthDiscoveryJwksQueryResult = NonNullable<
    Awaited<ReturnType<typeof oauthDiscoveryJwks>>
>;
export type OauthDiscoveryJwksQueryError = unknown;

/**
 * @summary Get the oauth server's public keys (JWKs)
 */

export function createOauthDiscoveryJwks<
    TData = Awaited<ReturnType<typeof oauthDiscoveryJwks>>,
    TError = unknown
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof oauthDiscoveryJwks>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getOauthDiscoveryJwksQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type tokenResponse200 = {
    data: TokenResponse;
    status: 200;
};

export type tokenResponse500 = {
    data: ApiError;
    status: 500;
};

export type tokenResponseSuccess = tokenResponse200 & {
    headers: Headers;
};
export type tokenResponseError = tokenResponse500 & {
    headers: Headers;
};

export type tokenResponse = tokenResponseSuccess | tokenResponseError;

export const getTokenUrl = () => {
    return `${apiUrlForOrval}/v1/oauth2/token`;
};

/**
 * @summary Exchange an authorization code for an access token
 */
export const token = async (
    tokenRequest: TokenRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<tokenResponse> => {
    const formUrlEncoded = new URLSearchParams();
    formUrlEncoded.append(`client_id`, tokenRequest.client_id);
    formUrlEncoded.append(`client_secret`, tokenRequest.client_secret);
    formUrlEncoded.append(`code`, tokenRequest.code);
    formUrlEncoded.append(`code_verifier`, tokenRequest.code_verifier);
    formUrlEncoded.append(`grant_type`, tokenRequest.grant_type);
    formUrlEncoded.append(`redirect_uri`, tokenRequest.redirect_uri);

    const res = await (fetchFn ?? fetch)(getTokenUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded", ...options?.headers },
        body: formUrlEncoded
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: tokenResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as tokenResponse;
};

export const getTokenMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof token>>,
        TError,
        { data: TokenRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof token>>,
    TError,
    { data: TokenRequest },
    TContext
> => {
    const mutationKey = ["token"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof token>>,
        { data: TokenRequest }
    > = (props) => {
        const { data } = props ?? {};

        return token(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type TokenMutationResult = NonNullable<Awaited<ReturnType<typeof token>>>;
export type TokenMutationBody = TokenRequest;
export type TokenMutationError = ApiError;

/**
 * @summary Exchange an authorization code for an access token
 */
export const createToken = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof token>>,
            TError,
            { data: TokenRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof token>>,
    TError,
    { data: TokenRequest },
    TContext
> => {
    return createMutation(() => ({ ...getTokenMutationOptions(options?.()) }), queryClient);
};
export type openidUserinfoResponse200 = {
    data: OpenIdUserInfo;
    status: 200;
};

export type openidUserinfoResponseSuccess = openidUserinfoResponse200 & {
    headers: Headers;
};

export type openidUserinfoResponse = openidUserinfoResponseSuccess;

export const getOpenidUserinfoUrl = () => {
    return `${apiUrlForOrval}/v1/oauth2/userinfo`;
};

/**
 * This handler requires that the token has the `openid` scope.
 * @summary Get the openid userinfo for the token's user.
 */
export const openidUserinfo = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<openidUserinfoResponse> => {
    const res = await (fetchFn ?? fetch)(getOpenidUserinfoUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: openidUserinfoResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as openidUserinfoResponse;
};

export const getOpenidUserinfoQueryKey = () => {
    return [`${apiUrlForOrval}/v1/oauth2/userinfo`] as const;
};

export const getOpenidUserinfoQueryOptions = <
    TData = Awaited<ReturnType<typeof openidUserinfo>>,
    TError = unknown
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof openidUserinfo>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getOpenidUserinfoQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof openidUserinfo>>> = ({ signal }) =>
        openidUserinfo({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof openidUserinfo>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OpenidUserinfoQueryResult = NonNullable<Awaited<ReturnType<typeof openidUserinfo>>>;
export type OpenidUserinfoQueryError = unknown;

/**
 * @summary Get the openid userinfo for the token's user.
 */

export function createOpenidUserinfo<
    TData = Awaited<ReturnType<typeof openidUserinfo>>,
    TError = unknown
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof openidUserinfo>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getOpenidUserinfoQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}
