/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type { ApiError, ListDataResponseSession, Session, UlidId } from "../model";

export type currentSessionInfoResponse200 = {
    data: Session;
    status: 200;
};

export type currentSessionInfoResponse500 = {
    data: ApiError;
    status: 500;
};

export type currentSessionInfoResponseSuccess = currentSessionInfoResponse200 & {
    headers: Headers;
};
export type currentSessionInfoResponseError = currentSessionInfoResponse500 & {
    headers: Headers;
};

export type currentSessionInfoResponse =
    | currentSessionInfoResponseSuccess
    | currentSessionInfoResponseError;

export const getCurrentSessionInfoUrl = () => {
    return `${apiUrlForOrval}/v1/me/session`;
};

/**
 * @summary Current session info
 */
export const currentSessionInfo = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<currentSessionInfoResponse> => {
    const res = await (fetchFn ?? fetch)(getCurrentSessionInfoUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: currentSessionInfoResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as currentSessionInfoResponse;
};

export const getCurrentSessionInfoQueryKey = () => {
    return [`${apiUrlForOrval}/v1/me/session`] as const;
};

export const getCurrentSessionInfoQueryOptions = <
    TData = Awaited<ReturnType<typeof currentSessionInfo>>,
    TError = ApiError
>(options?: {
    query?: Partial<
        CreateQueryOptions<Awaited<ReturnType<typeof currentSessionInfo>>, TError, TData>
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getCurrentSessionInfoQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof currentSessionInfo>>> = ({ signal }) =>
        currentSessionInfo({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof currentSessionInfo>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CurrentSessionInfoQueryResult = NonNullable<
    Awaited<ReturnType<typeof currentSessionInfo>>
>;
export type CurrentSessionInfoQueryError = ApiError;

/**
 * @summary Current session info
 */

export function createCurrentSessionInfo<
    TData = Awaited<ReturnType<typeof currentSessionInfo>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof currentSessionInfo>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getCurrentSessionInfoQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type revokeAllSessionsResponse200 = {
    data: void;
    status: 200;
};

export type revokeAllSessionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type revokeAllSessionsResponseSuccess = revokeAllSessionsResponse200 & {
    headers: Headers;
};
export type revokeAllSessionsResponseError = revokeAllSessionsResponse500 & {
    headers: Headers;
};

export type revokeAllSessionsResponse =
    | revokeAllSessionsResponseSuccess
    | revokeAllSessionsResponseError;

export const getRevokeAllSessionsUrl = () => {
    return `${apiUrlForOrval}/v1/me/session/all`;
};

/**
 * This includes your current one
 * @summary Close all your open sessions
 */
export const revokeAllSessions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<revokeAllSessionsResponse> => {
    const res = await (fetchFn ?? fetch)(getRevokeAllSessionsUrl(), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: revokeAllSessionsResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as revokeAllSessionsResponse;
};

export const getRevokeAllSessionsMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof revokeAllSessions>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof revokeAllSessions>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["revokeAllSessions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof revokeAllSessions>>,
        void
    > = () => {
        return revokeAllSessions(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type RevokeAllSessionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof revokeAllSessions>>
>;

export type RevokeAllSessionsMutationError = ApiError;

/**
 * @summary Close all your open sessions
 */
export const createRevokeAllSessions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof revokeAllSessions>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof revokeAllSessions>>, TError, void, TContext> => {
    return createMutation(
        () => ({ ...getRevokeAllSessionsMutationOptions(options?.()) }),
        queryClient
    );
};
export type listSessionsResponse200 = {
    data: ListDataResponseSession;
    status: 200;
};

export type listSessionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type listSessionsResponseSuccess = listSessionsResponse200 & {
    headers: Headers;
};
export type listSessionsResponseError = listSessionsResponse500 & {
    headers: Headers;
};

export type listSessionsResponse = listSessionsResponseSuccess | listSessionsResponseError;

export const getListSessionsUrl = () => {
    return `${apiUrlForOrval}/v1/me/session/list`;
};

/**
 * @summary List all your open sessions
 */
export const listSessions = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<listSessionsResponse> => {
    const res = await (fetchFn ?? fetch)(getListSessionsUrl(), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listSessionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as listSessionsResponse;
};

export const getListSessionsQueryKey = () => {
    return [`${apiUrlForOrval}/v1/me/session/list`] as const;
};

export const getListSessionsQueryOptions = <
    TData = Awaited<ReturnType<typeof listSessions>>,
    TError = ApiError
>(options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>>;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListSessionsQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessions>>> = ({ signal }) =>
        listSessions({ signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof listSessions>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof listSessions>>>;
export type ListSessionsQueryError = ApiError;

/**
 * @summary List all your open sessions
 */

export function createListSessions<
    TData = Awaited<ReturnType<typeof listSessions>>,
    TError = ApiError
>(
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof listSessions>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getListSessionsQueryOptions(options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type revokeSessionResponse200 = {
    data: void;
    status: 200;
};

export type revokeSessionResponse401 = {
    data: ApiError;
    status: 401;
};

export type revokeSessionResponse404 = {
    data: ApiError;
    status: 404;
};

export type revokeSessionResponse500 = {
    data: ApiError;
    status: 500;
};

export type revokeSessionResponseSuccess = revokeSessionResponse200 & {
    headers: Headers;
};
export type revokeSessionResponseError = (
    | revokeSessionResponse401
    | revokeSessionResponse404
    | revokeSessionResponse500
) & {
    headers: Headers;
};

export type revokeSessionResponse = revokeSessionResponseSuccess | revokeSessionResponseError;

export const getRevokeSessionUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/session/${id}`;
};

/**
 * @summary Close one of your sessions
 */
export const revokeSession = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<revokeSessionResponse> => {
    const res = await (fetchFn ?? fetch)(getRevokeSessionUrl(id), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: revokeSessionResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as revokeSessionResponse;
};

export const getRevokeSessionMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof revokeSession>>,
        TError,
        { id: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof revokeSession>>,
    TError,
    { id: UlidId },
    TContext
> => {
    const mutationKey = ["revokeSession"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof revokeSession>>,
        { id: UlidId }
    > = (props) => {
        const { id } = props ?? {};

        return revokeSession(id, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type RevokeSessionMutationResult = NonNullable<Awaited<ReturnType<typeof revokeSession>>>;

export type RevokeSessionMutationError = ApiError;

/**
 * @summary Close one of your sessions
 */
export const createRevokeSession = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof revokeSession>>,
            TError,
            { id: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof revokeSession>>,
    TError,
    { id: UlidId },
    TContext
> => {
    return createMutation(() => ({ ...getRevokeSessionMutationOptions(options?.()) }), queryClient);
};
