use std::{net::SocketAddr, path::Path};

use crate::crypto::{SecretKey, get_secret_key};
use anyhow::Context;
use clap::Parser;
use config::Config;
use smart_default::SmartDefault;
use toml_edit::{Document, DocumentMut};
use url::Url;

#[derive(
    SmartDefault, Debug, serde::Serialize, serde::Deserialize, meow_macros::ExtractStructDocs,
)]
pub struct Logging {
    #[default = true]
    pub enabled: bool,
    pub level: LoggingLevel,
}

#[derive(Default, Debug, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum LoggingLevel {
    #[default]
    Info,
    Warn,
    Error,
    Debug,
    Trace,
}

impl std::fmt::Display for LoggingLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            LoggingLevel::Info => "info",
            LoggingLevel::Warn => "warn",
            LoggingLevel::Error => "error",
            LoggingLevel::Debug => "debug",
            LoggingLevel::Trace => "trace",
        };
        write!(f, "{}", str)
    }
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct ApplicationSettings {
    /// How long, in seconds, services get to end their work before a forced shutdown
    #[default(Some(60*2))]
    pub shutdown_timeout_seconds: Option<u64>,
    /// Whether the app should force a shutdown after `shutdown_timeout_seconds`
    #[default(Some(true))]
    pub shutdown_timeout_enabled: Option<bool>,
    /// A 64 char long key used to encrypt and decrypt sensitive data (like TOTP secrets)
    /// Its autogenerated if left blank. Changing it makes anything encrypted before trash
    #[default(get_secret_key(32))]
    pub master_key: SecretKey,
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct HttpSettings {
    #[default(SocketAddr::from(([127,0,0,1],8080)))]
    pub bind: SocketAddr,
    pub api_docs: ApiDocsSettings,
    // must be always set, its where this application is running.
    /// The URL where this app is reachable. Its used to build absolute URLs (for OAuth), so it has
    /// to match the reachable URL exactly
    #[default(Url::parse("http://localhost:8080").expect("failed to parse default origin url burh"))]
    pub origin: Url,
    // must be always set, its where this application is running.
    /// The URL where the frontend is reachable. Its used for setting up CORS and Cookies
    #[default(Url::parse("http://localhost:3000").expect("failed to parse default frontend url burh"))]
    pub frontend: Url,
    /// Whether the app is running behind Cloudflare proxy (orange cloud). When its `true`, the app will read
    /// the connecting user ip from the `CF-Connecting-IP` header instead of the raw addr
    #[default(false)]
    pub is_under_cloudflare: bool,
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct ApiDocsSettings {
    #[default = true]
    pub enabled: bool,
    #[default("/scalar".to_string())]
    pub path: String,
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct DatabaseSettings {
    #[default("postgres://meow:meow_pwd@localhost:5432/meow2_development".to_string())]
    pub url: String,
    #[default = 1]
    pub min_connections: u32,
    #[default = 10]
    pub max_connections: u32,
}

// TODO: Should find a better name for this.
#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct SessionSettings {
    /// The name of the Cookie used to store the session id
    #[default("meow_sess")]
    pub cookie_name: String,
    /// The maximum lifetime of a session, in seconds, where it expires no matter if it was used recently
    #[default(60 * 60 * 24 * 30)]
    pub expire_age_seconds: i64,
    /// How long, in seconds, a session can last without any activity before being seen as expired
    #[default(60 * 60 * 24 * 7)]
    pub active_expire_age_seconds: i64,
    /// The threshold time, in seconds, before a session can be renewed
    #[default(60 * 10)]
    pub update_threshold_seconds: i64,
    /// How long, in seconds, a session's sudo (sensitive operations) mode can last
    #[default(60 * 15)]
    pub sudo_expire_age_seconds: i64,
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct MailerSettings {
    #[default("localhost".to_string())]
    pub smtp_host: String,
    pub smtp_username: String,
    pub smtp_password: String,
    #[default = 1025]
    pub smtp_port: u16,
    #[default = false]
    pub smtp_secure: bool,
    #[default("meow@meow.com".to_string())]
    pub from_email: String,
    /// Whether the app should check on start up and exit if the SMTP connection to the email server fails
    /// (eg. its unreachable)
    #[default = false]
    pub test_connection: bool,
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct TotpSettings {
    #[default("meow_auth".to_string())]
    pub issuer: String,
    #[default(6)]
    pub digits: u8,
}

#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct WebauthnSettings {
    /// The naked domain (no scheme or port AND not 127.0.0.1) where Webauthn (Passkey) operations are scoped in.
    /// For example, if our `rp_origin` is "http://localhost:8080", the `rp_id` should be only "localhost"
    #[default("localhost".to_string())]
    pub rp_id: String,
    #[default("MeowAuth".to_string())]
    pub rp_display_name: String,
    /// The origin URL (with scheme and port) where Webauthn (Passkey) operations are allowed to be done.
    /// For example, "http://localhost:8080" is an origin that can be used with the "localhost" `rp_id`
    #[default(Url::parse("http://localhost:8080").expect("failed to parse default origin url burh"))]
    pub rp_origin: Url,
    #[default(60*5)]
    pub timeout_seconds: i64,
}

/// not root docs (oauth)
#[derive(
    Debug, SmartDefault, serde::Serialize, serde::Deserialize, Clone, meow_macros::ExtractStructDocs,
)]
pub struct OauthSettings {
    /// How long, in seconds, the OIDC ID token lasts until expired
    #[default(60*60)]
    pub oidc_id_token_expire_seconds: i64,
    /// How long, in seconds, a signing key (JWK) is allowed to be used to sign new JWTs before its retired
    /// (Retired does not mean deleted, it still exists ONLY for JWT verification purposes)
    #[default(60*60*24*30*2)]
    pub jwk_active_seconds: i64,
    /// How long, in seconds, a retired JWK is still kept, so JWTs signed with it can still be verified, before it's
    /// deleted
    #[default(60*60*24*30*3)]
    pub jwk_expired_after_seconds: i64,
    /// How often, in seconds, its checked if the JWKs need to be rotated or deleted
    #[default(60*60*12)]
    pub jwk_cycle_after_seconds: i64,
}

/// Meow Auth settings :3
#[derive(Debug, Default, serde::Serialize, serde::Deserialize, meow_macros::ExtractStructDocs)]
pub struct Settings {
    #[serde(default)]
    pub application: ApplicationSettings,
    pub logging: Logging,
    pub http: HttpSettings,
    pub database: DatabaseSettings,
    pub mailer: MailerSettings,
    pub session: SessionSettings,
    pub totp: TotpSettings,
    pub webauthn: WebauthnSettings,
    pub oauth: OauthSettings,
}

impl Settings {
    pub fn new() -> anyhow::Result<Self> {
        dotenvy::dotenv().context("Failed to load .env* file")?;
        let environment = std::env::var("WORK_ENV").unwrap_or_else(|_| "development".to_string());
        println!("Loading settings for environment '{environment}'");
        // Self::create_if_not_exists(&environment)?; shouldn't be auto creating the file.
        let settings = Config::builder()
            .add_source(
                config::File::with_name(&format!("settings/{environment}.toml")).required(false),
            )
            .add_source(config::Environment::with_prefix("MEOW").separator("__"))
            .build()?;

        match settings.try_deserialize() {
            Ok(s) => Ok(s),
            Err(e) => Err(anyhow::anyhow!("Failed to parse settings: {}", e)),
        }
    }

    fn create_if_not_exists(env: &str) -> anyhow::Result<()> {
        let path = Path::new("settings").join(format!("{env}.toml"));

        if !path.exists() {
            std::fs::create_dir_all(Path::new("settings"))?;
            std::fs::write(&path, toml::to_string_pretty(&Self::default())?.as_bytes())?;
            println!("Settings file created at: {}", path.display());
        }

        Ok(())
    }
}

// good enough for now, i mean the thing is going to be always be called on startup of the app lol
#[derive(Debug, clap::Parser)]
struct UpdateCmd {
    /// Environment files to update.
    #[clap(long, short)]
    envs: Vec<String>,
    /// Delete keys that are not present in the default settings.
    #[clap(long, short)]
    delete_unknown_keys: bool,
}

pub fn update_cli() {
    match UpdateCmd::try_parse() {
        Ok(cmd) => {
            if cmd.envs.is_empty() {
                return;
            }

            for env in &cmd.envs {
                Settings::create_if_not_exists(env).expect("Failed creating settings file.");
                let path = Path::new("settings").join(format!("{}.toml", env));
                let contents =
                    std::fs::read_to_string(&path).expect("Failed to read settings file.");
                let current_toml = contents
                    .parse::<Document<String>>()
                    .expect("Failed to parse existing settings file.");

                let mut new_toml = toml::to_string_pretty(&Settings::default())
                    .expect("Failed to get new settings.")
                    .parse::<DocumentMut>()
                    .expect("Failed to parse new settings");

                println!("Starting update for '{env}'");
                update_toml_keys(&mut new_toml, &current_toml, cmd.delete_unknown_keys);
                add_root_docs(&mut new_toml);

                std::fs::write(path, new_toml.to_string().as_bytes())
                    .expect("Failed to write new settings file.");
                println!("Finished updating settings for environment '{env}'!")
            }
        }
        Err(e) => {
            eprintln!("Something went wrong! {}", e);
            std::process::exit(1)
        }
    }
}

fn update_toml_keys(
    new_toml: &mut toml_edit::DocumentMut,
    current_toml: &toml_edit::Document<String>,
    delete_unknown_keys: bool,
) {
    if delete_unknown_keys {
        println!("Heads up! Going to delete unknown keys in a blink of an eye")
    }
    for (key, value) in current_toml.iter() {
        if !new_toml.contains_key(key) {
            if delete_unknown_keys {
                let name = match value.is_table() {
                    true => "table",
                    false => "key",
                };
                println!("Removing unknown {name} from settings");
                continue;
            }

            if !value.is_table() {
                new_toml.insert(key, value.clone());
                continue;
            }
        }

        if value.is_table()
            && let Some(new_item) = new_toml.get_mut(key)
            && let (Some(new_table), Some(old_table)) = (new_item.as_table_mut(), value.as_table())
        {
            update_toml_table(new_table, old_table, delete_unknown_keys)
        }
    }
}

fn update_toml_table(
    new_table: &mut toml_edit::Table,
    old_table: &toml_edit::Table,
    delete_unknown_keys: bool,
) {
    for (key, value) in old_table.iter() {
        if let Some(new_value) = new_table.get_mut(key) {
            if new_value.is_table() && value.is_table() {
                update_toml_table(
                    new_value.as_table_mut().expect("should be a table"),
                    value.as_table().expect("should be a table"),
                    delete_unknown_keys,
                );
                continue;
            }

            *new_value = value.clone();
        } else {
            if delete_unknown_keys {
                let name = match value.is_table() {
                    true => "table",
                    false => "key",
                };
                println!("Removing unknown {name} '{}' from settings", key);
                continue;
            }

            new_table.insert(key, value.clone());
        }
    }
}

fn add_root_docs(toml_doc: &mut toml_edit::DocumentMut) {
    let root = Settings::DOCS;

    let root_docs = root
        .docs
        .iter()
        .map(|v| v.to_string())
        .map(|v| format!("# {v}"))
        .collect::<Vec<_>>()
        .join("\n");

    if !root_docs.trim().is_empty() {
        toml_doc.decor_mut().set_prefix(format!("{root_docs:}\n\n"));
    }
    add_table_docs(toml_doc.as_table_mut(), root);
}

fn add_table_docs(table: &mut toml_edit::Table, node: &DocNode) {
    for entry in node.children {
        let Some(item) = table.get_mut(entry.key) else {
            continue;
        };

        let docs = entry
            .node
            .docs
            .iter()
            .map(|v| v.to_string())
            .map(|v| format!("# {v}"))
            .collect::<Vec<_>>()
            .join("\n");

        if item.is_table() {
            let table = item.as_table_mut().expect("should be a table");
            if !docs.trim().is_empty() {
                table.decor_mut().set_prefix(format!("{docs:}\n"));
            }

            // greaet job bird brain. YOU HAVE tO CYCLE AGAIN OR ELSE table KEYS wont be even seen to add their docs STUPID
            add_table_docs(table, entry.node);
        } else if !docs.trim().is_empty()
            && let Some(mut key) = table.key_mut(entry.key)
        {
            key.leaf_decor_mut().set_prefix(format!("{docs:}\n"));
        }
    }
}

#[derive(Debug, Clone, Copy, Default)]
struct DocNode {
    /// the "docs" are the docs of the field it self. **They are used to generate the toml docs**
    /// Visually is this:
    ///
    /// ```rust
    /// // These docs are the "Docs" of the field child !!!!
    /// struct Parent {
    ///     child: Child,
    /// }
    ///
    /// // These docs are the "Type Docs" (ignored)
    /// struct Child {
    ///     baby: bool,
    /// }
    /// ```
    pub docs: &'static [&'static str],

    /// the "type docs" are the docs of the type of the field, not the docs of the field itself. **They are ignored
    /// when generating the toml docs.** Visually is this:
    ///
    /// ```rust
    /// // These docs are the "Type Docs" !!!! (ignored)
    /// struct Child {
    ///     baby: bool,
    /// }
    ///
    /// // These docs are the "Docs" of the field child
    /// struct Parent {
    ///     child: Child,
    /// }
    /// ```
    #[allow(dead_code, reason = "unused in toml doc generation")]
    pub type_docs: &'static [&'static str],

    /// the children of any struct are its fields. Like:
    /// ```rust
    /// // "small" and "goblin" are the children of the struct Bob.
    /// struct Bob {
    ///     small: bool,
    ///     goblin: bool,
    /// }
    /// ```
    /// But, those two childs, small and goblin, do not have children of their own becuase they are normal types (Like
    /// u32, i64, String...).
    ///
    /// BUTT, one field can have children of its own IF its a nested struct. Like:
    /// ```rust
    /// // now Bob has as its children "small" and "mouth"!
    /// struct Bob {
    ///     small: bool,  // No children here!
    ///     mouth: Mouth, // CHILDREN!! Because its a nested struct!
    /// }
    /// // Both of Mouth's struct fields are typical types, so no children.
    /// struct Mouth {
    ///     open: bool,
    ///     show_tonge: bool,
    /// }
    /// ```
    ///
    /// Its practically packaging something inside one box and then putting it inside another box with related things.
    /// one might say "its being organized cleanly"!... (no it isnt, this space birb does not approve :[)
    pub children: &'static [DocEntry],
}

#[derive(Debug, Clone, Copy)]
struct DocEntry {
    pub key: &'static str,
    pub node: &'static DocNode,
}

trait HasDocs {
    const DOCS: &'static DocNode;
}

impl<T: HasDocs> HasDocs for Option<T> {
    const DOCS: &'static DocNode = T::DOCS;
}

/// implements an empty DocNode for types that dont really have docs
macro_rules! doc_node_ignore {
    ($($ty:ty),*) => {
        $(impl HasDocs for $ty {
            const DOCS: &'static DocNode = &DocNode {
                docs: &[],
                type_docs: &[],
                children: &[]
            };
        })*
    };
}

doc_node_ignore!(
    u8,
    u16,
    u32,
    u64,
    u128,
    usize,
    i8,
    i16,
    i32,
    i64,
    i128,
    isize,
    f32,
    f64,
    bool,
    char,
    String,
    &str,
    LoggingLevel,
    Url,
    SocketAddr,
    SecretKey
);
