/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    MutationFunction,
    QueryClient
} from "@tanstack/svelte-query";

import type {
    AlrightResponse,
    ApiError,
    AuthenticationPasskeyRequest,
    ExchangeRequest,
    FlowOptionResponse,
    FlowRequest,
    FlowResponse,
    RegisterRequest,
    _OtpExchangeResponse
} from "../model";

export type flowOptionsResponse200 = {
    data: FlowOptionResponse;
    status: 200;
};

export type flowOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowOptionsResponseSuccess = flowOptionsResponse200 & {
    headers: Headers;
};
export type flowOptionsResponseError = flowOptionsResponse500 & {
    headers: Headers;
};

export type flowOptionsResponse = flowOptionsResponseSuccess | flowOptionsResponseError;

export const getFlowOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow`;
};

/**
 * Requests what authentications methods you can use to authenticate with the given login.
 * This is useful for determining if a user has a passkey or not
 * @summary Get the Authentication options
 */
export const flowOptions = async (
    flowRequest: FlowRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getFlowOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(flowRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowOptionsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowOptionsResponse;
};

export const getFlowOptionsMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowOptions>>,
        TError,
        { data: FlowRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowOptions>>,
    TError,
    { data: FlowRequest },
    TContext
> => {
    const mutationKey = ["flowOptions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowOptions>>,
        { data: FlowRequest }
    > = (props) => {
        const { data } = props ?? {};

        return flowOptions(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowOptionsMutationResult = NonNullable<Awaited<ReturnType<typeof flowOptions>>>;
export type FlowOptionsMutationBody = FlowRequest;
export type FlowOptionsMutationError = ApiError;

/**
 * @summary Get the Authentication options
 */
export const createFlowOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowOptions>>,
            TError,
            { data: FlowRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowOptions>>,
    TError,
    { data: FlowRequest },
    TContext
> => {
    return createMutation(() => ({ ...getFlowOptionsMutationOptions(options?.()) }), queryClient);
};
export type flowOtpExchangeResponse200 = {
    data: _OtpExchangeResponse;
    status: 200;
};

export type flowOtpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type flowOtpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowOtpExchangeResponseSuccess = flowOtpExchangeResponse200 & {
    headers: Headers;
};
export type flowOtpExchangeResponseError = (
    | flowOtpExchangeResponse401
    | flowOtpExchangeResponse500
) & {
    headers: Headers;
};

export type flowOtpExchangeResponse = flowOtpExchangeResponseSuccess | flowOtpExchangeResponseError;

export const getFlowOtpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/exchange`;
};

/**
 * This can be also requested by a user registering a new account.
 * The response can return a `next_method: ["totp"]` if the user has TOTP enabled.
 * @summary Exchange the Authentication Flow ID made by an OTP code
 */
export const flowOtpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowOtpExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getFlowOtpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowOtpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowOtpExchangeResponse;
};

export const getFlowOtpExchangeMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowOtpExchange>>,
        TError,
        { data: ExchangeRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowOtpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    const mutationKey = ["flowOtpExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowOtpExchange>>,
        { data: ExchangeRequest }
    > = (props) => {
        const { data } = props ?? {};

        return flowOtpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowOtpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowOtpExchange>>
>;
export type FlowOtpExchangeMutationBody = ExchangeRequest;
export type FlowOtpExchangeMutationError = ApiError;

/**
 * @summary Exchange the Authentication Flow ID made by an OTP code
 */
export const createFlowOtpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowOtpExchange>>,
            TError,
            { data: ExchangeRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowOtpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowOtpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type flowTotpExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type flowTotpExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type flowTotpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type flowTotpExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type flowTotpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowTotpExchangeResponseSuccess = flowTotpExchangeResponse200 & {
    headers: Headers;
};
export type flowTotpExchangeResponseError = (
    | flowTotpExchangeResponse400
    | flowTotpExchangeResponse401
    | flowTotpExchangeResponse404
    | flowTotpExchangeResponse500
) & {
    headers: Headers;
};

export type flowTotpExchangeResponse =
    | flowTotpExchangeResponseSuccess
    | flowTotpExchangeResponseError;

export const getFlowTotpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/exchange/totp`;
};

/**
 * @summary Exchange the Authentication Flow ID made by an enabled TOTP
 */
export const flowTotpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowTotpExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getFlowTotpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowTotpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowTotpExchangeResponse;
};

export const getFlowTotpExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowTotpExchange>>,
        TError,
        { data: ExchangeRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowTotpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    const mutationKey = ["flowTotpExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowTotpExchange>>,
        { data: ExchangeRequest }
    > = (props) => {
        const { data } = props ?? {};

        return flowTotpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowTotpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowTotpExchange>>
>;
export type FlowTotpExchangeMutationBody = ExchangeRequest;
export type FlowTotpExchangeMutationError = ApiError;

/**
 * @summary Exchange the Authentication Flow ID made by an enabled TOTP
 */
export const createFlowTotpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowTotpExchange>>,
            TError,
            { data: ExchangeRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowTotpExchange>>,
    TError,
    { data: ExchangeRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowTotpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type flowWebauthnExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type flowWebauthnExchangeResponse403 = {
    data: ApiError;
    status: 403;
};

export type flowWebauthnExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type flowWebauthnExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowWebauthnExchangeResponseSuccess = flowWebauthnExchangeResponse200 & {
    headers: Headers;
};
export type flowWebauthnExchangeResponseError = (
    | flowWebauthnExchangeResponse403
    | flowWebauthnExchangeResponse404
    | flowWebauthnExchangeResponse500
) & {
    headers: Headers;
};

export type flowWebauthnExchangeResponse =
    | flowWebauthnExchangeResponseSuccess
    | flowWebauthnExchangeResponseError;

export const getFlowWebauthnExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/exchange/webauthn`;
};

/**
 * @summary Exchange the Authentication Flow made by a Passkey browser challenge
 */
export const flowWebauthnExchange = async (
    authenticationPasskeyRequest: AuthenticationPasskeyRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowWebauthnExchangeResponse> => {
    const res = await (fetchFn ?? fetch)(getFlowWebauthnExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(authenticationPasskeyRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowWebauthnExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowWebauthnExchangeResponse;
};

export const getFlowWebauthnExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowWebauthnExchange>>,
        TError,
        { data: AuthenticationPasskeyRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowWebauthnExchange>>,
    TError,
    { data: AuthenticationPasskeyRequest },
    TContext
> => {
    const mutationKey = ["flowWebauthnExchange"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowWebauthnExchange>>,
        { data: AuthenticationPasskeyRequest }
    > = (props) => {
        const { data } = props ?? {};

        return flowWebauthnExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowWebauthnExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowWebauthnExchange>>
>;
export type FlowWebauthnExchangeMutationBody = AuthenticationPasskeyRequest;
export type FlowWebauthnExchangeMutationError = ApiError;

/**
 * @summary Exchange the Authentication Flow made by a Passkey browser challenge
 */
export const createFlowWebauthnExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowWebauthnExchange>>,
            TError,
            { data: AuthenticationPasskeyRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowWebauthnExchange>>,
    TError,
    { data: AuthenticationPasskeyRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowWebauthnExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type otpLoginResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type otpLoginResponse500 = {
    data: ApiError;
    status: 500;
};

export type otpLoginResponseSuccess = otpLoginResponse200 & {
    headers: Headers;
};
export type otpLoginResponseError = otpLoginResponse500 & {
    headers: Headers;
};

export type otpLoginResponse = otpLoginResponseSuccess | otpLoginResponseError;

export const getOtpLoginUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/start`;
};

/**
 * Starts the flow to authenticate via an OTP sent to the user's email
 * @summary Authenticate via an OTP code
 */
export const otpLogin = async (
    flowRequest: FlowRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<otpLoginResponse> => {
    const res = await (fetchFn ?? fetch)(getOtpLoginUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(flowRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: otpLoginResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as otpLoginResponse;
};

export const getOtpLoginMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof otpLogin>>,
        TError,
        { data: FlowRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof otpLogin>>,
    TError,
    { data: FlowRequest },
    TContext
> => {
    const mutationKey = ["otpLogin"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof otpLogin>>,
        { data: FlowRequest }
    > = (props) => {
        const { data } = props ?? {};

        return otpLogin(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type OtpLoginMutationResult = NonNullable<Awaited<ReturnType<typeof otpLogin>>>;
export type OtpLoginMutationBody = FlowRequest;
export type OtpLoginMutationError = ApiError;

/**
 * @summary Authenticate via an OTP code
 */
export const createOtpLogin = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof otpLogin>>,
            TError,
            { data: FlowRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof otpLogin>>,
    TError,
    { data: FlowRequest },
    TContext
> => {
    return createMutation(() => ({ ...getOtpLoginMutationOptions(options?.()) }), queryClient);
};
export type otpRegisterResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type otpRegisterResponse500 = {
    data: ApiError;
    status: 500;
};

export type otpRegisterResponseSuccess = otpRegisterResponse200 & {
    headers: Headers;
};
export type otpRegisterResponseError = otpRegisterResponse500 & {
    headers: Headers;
};

export type otpRegisterResponse = otpRegisterResponseSuccess | otpRegisterResponseError;

export const getOtpRegisterUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/start/register`;
};

/**
 * Starts the flow to register a new account via an OTP sent to the user's email.
 * Used on the same exchange endpoint as the authentication OTP code flow.
 * @summary Register a new account via an OTP code
 */
export const otpRegister = async (
    registerRequest: RegisterRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<otpRegisterResponse> => {
    const res = await (fetchFn ?? fetch)(getOtpRegisterUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(registerRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: otpRegisterResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as otpRegisterResponse;
};

export const getOtpRegisterMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof otpRegister>>,
        TError,
        { data: RegisterRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof otpRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
> => {
    const mutationKey = ["otpRegister"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof otpRegister>>,
        { data: RegisterRequest }
    > = (props) => {
        const { data } = props ?? {};

        return otpRegister(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type OtpRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof otpRegister>>>;
export type OtpRegisterMutationBody = RegisterRequest;
export type OtpRegisterMutationError = ApiError;

/**
 * @summary Register a new account via an OTP code
 */
export const createOtpRegister = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof otpRegister>>,
            TError,
            { data: RegisterRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof otpRegister>>,
    TError,
    { data: RegisterRequest },
    TContext
> => {
    return createMutation(() => ({ ...getOtpRegisterMutationOptions(options?.()) }), queryClient);
};
export type webauthnOptionsResponse200 = {
    data: void;
    status: 200;
};

export type webauthnOptionsResponse400 = {
    data: ApiError;
    status: 400;
};

export type webauthnOptionsResponse500 = {
    data: ApiError;
    status: 500;
};

export type webauthnOptionsResponseSuccess = webauthnOptionsResponse200 & {
    headers: Headers;
};
export type webauthnOptionsResponseError = (
    | webauthnOptionsResponse400
    | webauthnOptionsResponse500
) & {
    headers: Headers;
};

export type webauthnOptionsResponse = webauthnOptionsResponseSuccess | webauthnOptionsResponseError;

export const getWebauthnOptionsUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/start/webauthn`;
};

/**
 * Returns the challenge for the user's browser to use to authenticate.
 * @summary Authenticate via a Passkey
 */
export const webauthnOptions = async (
    flowRequest: FlowRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<webauthnOptionsResponse> => {
    const res = await (fetchFn ?? fetch)(getWebauthnOptionsUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(flowRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: webauthnOptionsResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as webauthnOptionsResponse;
};

export const getWebauthnOptionsMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof webauthnOptions>>,
        TError,
        { data: FlowRequest },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof webauthnOptions>>,
    TError,
    { data: FlowRequest },
    TContext
> => {
    const mutationKey = ["webauthnOptions"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof webauthnOptions>>,
        { data: FlowRequest }
    > = (props) => {
        const { data } = props ?? {};

        return webauthnOptions(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type WebauthnOptionsMutationResult = NonNullable<
    Awaited<ReturnType<typeof webauthnOptions>>
>;
export type WebauthnOptionsMutationBody = FlowRequest;
export type WebauthnOptionsMutationError = ApiError;

/**
 * @summary Authenticate via a Passkey
 */
export const createWebauthnOptions = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof webauthnOptions>>,
            TError,
            { data: FlowRequest },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof webauthnOptions>>,
    TError,
    { data: FlowRequest },
    TContext
> => {
    return createMutation(
        () => ({ ...getWebauthnOptionsMutationOptions(options?.()) }),
        queryClient
    );
};
