/**
 * Generated by orval 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    MutationFunction,
    QueryClient
} from "@tanstack/svelte-query";

import type {
    AlrightResponse,
    ApiError,
    AuthenticationPasskeyRequest,
    ExchangeRequest,
    FlowRequest,
    FlowResponse,
    RegisterRequest,
    StartChallengeResponse,
    _OtpExchangeResponse
} from "../model";

export type flowOtpExchangeResponse200 = {
    data: _OtpExchangeResponse;
    status: 200;
};

export type flowOtpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type flowOtpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowOtpExchangeResponseSuccess = flowOtpExchangeResponse200 & {
    headers: Headers;
};
export type flowOtpExchangeResponseError = (
    | flowOtpExchangeResponse401
    | flowOtpExchangeResponse500
) & {
    headers: Headers;
};

export type flowOtpExchangeResponse = flowOtpExchangeResponseSuccess | flowOtpExchangeResponseError;

export const getFlowOtpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/exchange`;
};

/**
 * This can be also requested by a user registering a new account.
 * The response can return a `next_method: ["totp"]` if the user has TOTP enabled.
 * @summary Exchange the Authentication Flow ID made by an OTP code
 */
export const flowOtpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowOtpExchangeResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getFlowOtpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowOtpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowOtpExchangeResponse;
};

export const getFlowOtpExchangeMutationKey = () => ["flowOtpExchange"] as const;

export const getFlowOtpExchangeMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowOtpExchange>>,
        TError,
        FlowOtpExchangeMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowOtpExchange>>,
    TError,
    FlowOtpExchangeMutationVariables,
    TContext
> => {
    const mutationKey = getFlowOtpExchangeMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowOtpExchange>>,
        FlowOtpExchangeMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return flowOtpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowOtpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowOtpExchange>>
>;
export type FlowOtpExchangeMutationBody = ExchangeRequest;
export type FlowOtpExchangeMutationError = ApiError;
export type FlowOtpExchangeMutationVariables = { data: ExchangeRequest };

/**
 * @summary Exchange the Authentication Flow ID made by an OTP code
 */
export const createFlowOtpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowOtpExchange>>,
            TError,
            FlowOtpExchangeMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowOtpExchange>>,
    TError,
    FlowOtpExchangeMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowOtpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type flowTotpExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type flowTotpExchangeResponse400 = {
    data: ApiError;
    status: 400;
};

export type flowTotpExchangeResponse401 = {
    data: ApiError;
    status: 401;
};

export type flowTotpExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type flowTotpExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowTotpExchangeResponseSuccess = flowTotpExchangeResponse200 & {
    headers: Headers;
};
export type flowTotpExchangeResponseError = (
    | flowTotpExchangeResponse400
    | flowTotpExchangeResponse401
    | flowTotpExchangeResponse404
    | flowTotpExchangeResponse500
) & {
    headers: Headers;
};

export type flowTotpExchangeResponse =
    | flowTotpExchangeResponseSuccess
    | flowTotpExchangeResponseError;

export const getFlowTotpExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/exchange/totp`;
};

/**
 * @summary Exchange the Authentication Flow ID made by an enabled TOTP
 */
export const flowTotpExchange = async (
    exchangeRequest: ExchangeRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowTotpExchangeResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getFlowTotpExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(exchangeRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowTotpExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowTotpExchangeResponse;
};

export const getFlowTotpExchangeMutationKey = () => ["flowTotpExchange"] as const;

export const getFlowTotpExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowTotpExchange>>,
        TError,
        FlowTotpExchangeMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowTotpExchange>>,
    TError,
    FlowTotpExchangeMutationVariables,
    TContext
> => {
    const mutationKey = getFlowTotpExchangeMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowTotpExchange>>,
        FlowTotpExchangeMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return flowTotpExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowTotpExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowTotpExchange>>
>;
export type FlowTotpExchangeMutationBody = ExchangeRequest;
export type FlowTotpExchangeMutationError = ApiError;
export type FlowTotpExchangeMutationVariables = { data: ExchangeRequest };

/**
 * @summary Exchange the Authentication Flow ID made by an enabled TOTP
 */
export const createFlowTotpExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowTotpExchange>>,
            TError,
            FlowTotpExchangeMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowTotpExchange>>,
    TError,
    FlowTotpExchangeMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowTotpExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type flowWebauthnExchangeResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type flowWebauthnExchangeResponse403 = {
    data: ApiError;
    status: 403;
};

export type flowWebauthnExchangeResponse404 = {
    data: ApiError;
    status: 404;
};

export type flowWebauthnExchangeResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowWebauthnExchangeResponseSuccess = flowWebauthnExchangeResponse200 & {
    headers: Headers;
};
export type flowWebauthnExchangeResponseError = (
    | flowWebauthnExchangeResponse403
    | flowWebauthnExchangeResponse404
    | flowWebauthnExchangeResponse500
) & {
    headers: Headers;
};

export type flowWebauthnExchangeResponse =
    | flowWebauthnExchangeResponseSuccess
    | flowWebauthnExchangeResponseError;

export const getFlowWebauthnExchangeUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/exchange/webauthn`;
};

/**
 * @summary Exchange the Authentication Flow made by a Passkey browser challenge
 */
export const flowWebauthnExchange = async (
    authenticationPasskeyRequest: AuthenticationPasskeyRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowWebauthnExchangeResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getFlowWebauthnExchangeUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(authenticationPasskeyRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowWebauthnExchangeResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowWebauthnExchangeResponse;
};

export const getFlowWebauthnExchangeMutationKey = () => ["flowWebauthnExchange"] as const;

export const getFlowWebauthnExchangeMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowWebauthnExchange>>,
        TError,
        FlowWebauthnExchangeMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowWebauthnExchange>>,
    TError,
    FlowWebauthnExchangeMutationVariables,
    TContext
> => {
    const mutationKey = getFlowWebauthnExchangeMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowWebauthnExchange>>,
        FlowWebauthnExchangeMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return flowWebauthnExchange(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowWebauthnExchangeMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowWebauthnExchange>>
>;
export type FlowWebauthnExchangeMutationBody = AuthenticationPasskeyRequest;
export type FlowWebauthnExchangeMutationError = ApiError;
export type FlowWebauthnExchangeMutationVariables = { data: AuthenticationPasskeyRequest };

/**
 * @summary Exchange the Authentication Flow made by a Passkey browser challenge
 */
export const createFlowWebauthnExchange = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowWebauthnExchange>>,
            TError,
            FlowWebauthnExchangeMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowWebauthnExchange>>,
    TError,
    FlowWebauthnExchangeMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowWebauthnExchangeMutationOptions(options?.()) }),
        queryClient
    );
};
export type flowOtpStartResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type flowOtpStartResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowOtpStartResponseSuccess = flowOtpStartResponse200 & {
    headers: Headers;
};
export type flowOtpStartResponseError = flowOtpStartResponse500 & {
    headers: Headers;
};

export type flowOtpStartResponse = flowOtpStartResponseSuccess | flowOtpStartResponseError;

export const getFlowOtpStartUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/start`;
};

/**
 * Starts the flow to authenticate via an OTP sent to the user's email
 * @summary Authenticate via an OTP code
 */
export const flowOtpStart = async (
    flowRequest: FlowRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowOtpStartResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getFlowOtpStartUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(flowRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowOtpStartResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowOtpStartResponse;
};

export const getFlowOtpStartMutationKey = () => ["flowOtpStart"] as const;

export const getFlowOtpStartMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowOtpStart>>,
        TError,
        FlowOtpStartMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowOtpStart>>,
    TError,
    FlowOtpStartMutationVariables,
    TContext
> => {
    const mutationKey = getFlowOtpStartMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowOtpStart>>,
        FlowOtpStartMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return flowOtpStart(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowOtpStartMutationResult = NonNullable<Awaited<ReturnType<typeof flowOtpStart>>>;
export type FlowOtpStartMutationBody = FlowRequest;
export type FlowOtpStartMutationError = ApiError;
export type FlowOtpStartMutationVariables = { data: FlowRequest };

/**
 * @summary Authenticate via an OTP code
 */
export const createFlowOtpStart = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowOtpStart>>,
            TError,
            FlowOtpStartMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowOtpStart>>,
    TError,
    FlowOtpStartMutationVariables,
    TContext
> => {
    return createMutation(() => ({ ...getFlowOtpStartMutationOptions(options?.()) }), queryClient);
};
export type flowOtpRegisterResponse200 = {
    data: FlowResponse;
    status: 200;
};

export type flowOtpRegisterResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowOtpRegisterResponseSuccess = flowOtpRegisterResponse200 & {
    headers: Headers;
};
export type flowOtpRegisterResponseError = flowOtpRegisterResponse500 & {
    headers: Headers;
};

export type flowOtpRegisterResponse = flowOtpRegisterResponseSuccess | flowOtpRegisterResponseError;

export const getFlowOtpRegisterUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/start/register`;
};

/**
 * Starts the flow to register a new account via an OTP sent to the user's email.
 * Used on the same exchange endpoint as the authentication OTP code flow.
 * @summary Register a new account via an OTP code
 */
export const flowOtpRegister = async (
    registerRequest: RegisterRequest,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowOtpRegisterResponse> => {
    const getHeaders = (
        h?: NonNullable<RequestInit["headers"]>
    ): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(
                Array.from(
                    h as Iterable<Iterable<string>>,
                    (entry) => Array.from(entry) as [string, string]
                )
            );
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    const res = await (fetchFn ?? fetch)(getFlowOtpRegisterUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(registerRequest)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowOtpRegisterResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowOtpRegisterResponse;
};

export const getFlowOtpRegisterMutationKey = () => ["flowOtpRegister"] as const;

export const getFlowOtpRegisterMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowOtpRegister>>,
        TError,
        FlowOtpRegisterMutationVariables,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowOtpRegister>>,
    TError,
    FlowOtpRegisterMutationVariables,
    TContext
> => {
    const mutationKey = getFlowOtpRegisterMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowOtpRegister>>,
        FlowOtpRegisterMutationVariables
    > = (props) => {
        const { data } = props ?? {};

        return flowOtpRegister(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowOtpRegisterMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowOtpRegister>>
>;
export type FlowOtpRegisterMutationBody = RegisterRequest;
export type FlowOtpRegisterMutationError = ApiError;
export type FlowOtpRegisterMutationVariables = { data: RegisterRequest };

/**
 * @summary Register a new account via an OTP code
 */
export const createFlowOtpRegister = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowOtpRegister>>,
            TError,
            FlowOtpRegisterMutationVariables,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof flowOtpRegister>>,
    TError,
    FlowOtpRegisterMutationVariables,
    TContext
> => {
    return createMutation(
        () => ({ ...getFlowOtpRegisterMutationOptions(options?.()) }),
        queryClient
    );
};
export type flowWebauthnStartResponse200 = {
    data: StartChallengeResponse;
    status: 200;
};

export type flowWebauthnStartResponse400 = {
    data: ApiError;
    status: 400;
};

export type flowWebauthnStartResponse500 = {
    data: ApiError;
    status: 500;
};

export type flowWebauthnStartResponseSuccess = flowWebauthnStartResponse200 & {
    headers: Headers;
};
export type flowWebauthnStartResponseError = (
    | flowWebauthnStartResponse400
    | flowWebauthnStartResponse500
) & {
    headers: Headers;
};

export type flowWebauthnStartResponse =
    | flowWebauthnStartResponseSuccess
    | flowWebauthnStartResponseError;

export const getFlowWebauthnStartUrl = () => {
    return `${apiUrlForOrval}/v1/auth/flow/start/webauthn`;
};

/**
 * Returns the challenge for the user's browser to use to authenticate.
 * @summary Authenticate via a Passkey
 */
export const flowWebauthnStart = async (
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<flowWebauthnStartResponse> => {
    const res = await (fetchFn ?? fetch)(getFlowWebauthnStartUrl(), {
        credentials: "include",
        ...options,
        method: "POST"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: flowWebauthnStartResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as flowWebauthnStartResponse;
};

export const getFlowWebauthnStartMutationKey = () => ["flowWebauthnStart"] as const;

export const getFlowWebauthnStartMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof flowWebauthnStart>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof flowWebauthnStart>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = getFlowWebauthnStartMutationKey();
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof flowWebauthnStart>>,
        void
    > = () => {
        return flowWebauthnStart(fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type FlowWebauthnStartMutationResult = NonNullable<
    Awaited<ReturnType<typeof flowWebauthnStart>>
>;

export type FlowWebauthnStartMutationError = ApiError;

/**
 * @summary Authenticate via a Passkey
 */
export const createFlowWebauthnStart = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof flowWebauthnStart>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<Awaited<ReturnType<typeof flowWebauthnStart>>, TError, void, TContext> => {
    return createMutation(
        () => ({ ...getFlowWebauthnStartMutationOptions(options?.()) }),
        queryClient
    );
};
