/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * meow_auth2
 * OpenAPI spec version: 0.1.1
 */
import { apiUrlForOrval } from "$lib/api/ignoreThisPlease";
import { createMutation, createQuery } from "@tanstack/svelte-query";
import type {
    CreateMutationOptions,
    CreateMutationResult,
    CreateQueryOptions,
    CreateQueryResult,
    DataTag,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey
} from "@tanstack/svelte-query";

import type {
    AlrightResponse,
    ApiError,
    ListApplicationsParams,
    ListDataResponseOauthApplication,
    ListOauthAuthorizationsParams,
    OauthApplication,
    OauthApplicationData,
    OauthApplicationDataResponse,
    UlidId
} from "../model";

export type createApplicationResponse200 = {
    data: OauthApplicationDataResponse;
    status: 200;
};

export type createApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type createApplicationResponseSuccess = createApplicationResponse200 & {
    headers: Headers;
};
export type createApplicationResponseError = createApplicationResponse500 & {
    headers: Headers;
};

export type createApplicationResponse =
    | createApplicationResponseSuccess
    | createApplicationResponseError;

export const getCreateApplicationUrl = () => {
    return `${apiUrlForOrval}/v1/me/oauth/application/create`;
};

/**
 * @summary Create a new oauth application
 */
export const createApplication = async (
    oauthApplicationData: OauthApplicationData,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<createApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getCreateApplicationUrl(), {
        credentials: "include",
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(oauthApplicationData)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: createApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as createApplicationResponse;
};

export const getCreateApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof createApplication>>,
        TError,
        { data: OauthApplicationData },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof createApplication>>,
    TError,
    { data: OauthApplicationData },
    TContext
> => {
    const mutationKey = ["createApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createApplication>>,
        { data: OauthApplicationData }
    > = (props) => {
        const { data } = props ?? {};

        return createApplication(data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type CreateApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof createApplication>>
>;
export type CreateApplicationMutationBody = OauthApplicationData;
export type CreateApplicationMutationError = ApiError;

/**
 * @summary Create a new oauth application
 */
export const createCreateApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof createApplication>>,
            TError,
            { data: OauthApplicationData },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof createApplication>>,
    TError,
    { data: OauthApplicationData },
    TContext
> => {
    return createMutation(
        () => ({ ...getCreateApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type listApplicationsResponse200 = {
    data: ListDataResponseOauthApplication;
    status: 200;
};

export type listApplicationsResponse500 = {
    data: ApiError;
    status: 500;
};

export type listApplicationsResponseSuccess = listApplicationsResponse200 & {
    headers: Headers;
};
export type listApplicationsResponseError = listApplicationsResponse500 & {
    headers: Headers;
};

export type listApplicationsResponse =
    | listApplicationsResponseSuccess
    | listApplicationsResponseError;

export const getListApplicationsUrl = (params?: ListApplicationsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `${apiUrlForOrval}/v1/me/oauth/application/list?${stringifiedParams}`
        : `${apiUrlForOrval}/v1/me/oauth/application/list`;
};

/**
 * @summary List your oauth applications
 */
export const listApplications = async (
    params?: ListApplicationsParams,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<listApplicationsResponse> => {
    const res = await (fetchFn ?? fetch)(getListApplicationsUrl(params), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listApplicationsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as listApplicationsResponse;
};

export const getListApplicationsQueryKey = (params?: ListApplicationsParams) => {
    return [`${apiUrlForOrval}/v1/me/oauth/application/list`, ...(params ? [params] : [])] as const;
};

export const getListApplicationsQueryOptions = <
    TData = Awaited<ReturnType<typeof listApplications>>,
    TError = ApiError
>(
    params?: ListApplicationsParams,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof listApplications>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListApplicationsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listApplications>>> = ({ signal }) =>
        listApplications(params, { signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof listApplications>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListApplicationsQueryResult = NonNullable<Awaited<ReturnType<typeof listApplications>>>;
export type ListApplicationsQueryError = ApiError;

/**
 * @summary List your oauth applications
 */

export function createListApplications<
    TData = Awaited<ReturnType<typeof listApplications>>,
    TError = ApiError
>(
    params?: () => ListApplicationsParams,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof listApplications>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getListApplicationsQueryOptions(params?.(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type getInfoApplicationResponse200 = {
    data: OauthApplication;
    status: 200;
};

export type getInfoApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type getInfoApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type getInfoApplicationResponseSuccess = getInfoApplicationResponse200 & {
    headers: Headers;
};
export type getInfoApplicationResponseError = (
    | getInfoApplicationResponse404
    | getInfoApplicationResponse500
) & {
    headers: Headers;
};

export type getInfoApplicationResponse =
    | getInfoApplicationResponseSuccess
    | getInfoApplicationResponseError;

export const getGetInfoApplicationUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/oauth/application/${id}`;
};

/**
 * @summary Get info about a specific oauth application
 */
export const getInfoApplication = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<getInfoApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getGetInfoApplicationUrl(id), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getInfoApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as getInfoApplicationResponse;
};

export const getGetInfoApplicationQueryKey = (id: UlidId) => {
    return [`${apiUrlForOrval}/v1/me/oauth/application/${id}`] as const;
};

export const getGetInfoApplicationQueryOptions = <
    TData = Awaited<ReturnType<typeof getInfoApplication>>,
    TError = ApiError
>(
    id: UlidId,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof getInfoApplication>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetInfoApplicationQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInfoApplication>>> = ({ signal }) =>
        getInfoApplication(id, { signal, ...fetchOptions }, fetcherFn);

    return {
        queryKey,
        queryFn,
        enabled: id !== null && id !== undefined,
        ...queryOptions
    } as CreateQueryOptions<Awaited<ReturnType<typeof getInfoApplication>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type GetInfoApplicationQueryResult = NonNullable<
    Awaited<ReturnType<typeof getInfoApplication>>
>;
export type GetInfoApplicationQueryError = ApiError;

/**
 * @summary Get info about a specific oauth application
 */

export function createGetInfoApplication<
    TData = Awaited<ReturnType<typeof getInfoApplication>>,
    TError = ApiError
>(
    id: () => UlidId,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof getInfoApplication>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getGetInfoApplicationQueryOptions(id(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type deleteApplicationResponse200 = {
    data: void;
    status: 200;
};

export type deleteApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type deleteApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type deleteApplicationResponseSuccess = deleteApplicationResponse200 & {
    headers: Headers;
};
export type deleteApplicationResponseError = (
    | deleteApplicationResponse404
    | deleteApplicationResponse500
) & {
    headers: Headers;
};

export type deleteApplicationResponse =
    | deleteApplicationResponseSuccess
    | deleteApplicationResponseError;

export const getDeleteApplicationUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/oauth/application/${id}`;
};

/**
 * @summary Delete an existing oauth application
 */
export const deleteApplication = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<deleteApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getDeleteApplicationUrl(id), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteApplicationResponse["data"] = body ? JSON.parse(body) : undefined;
    return { data, status: res.status, headers: res.headers } as deleteApplicationResponse;
};

export const getDeleteApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof deleteApplication>>,
        TError,
        { id: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof deleteApplication>>,
    TError,
    { id: UlidId },
    TContext
> => {
    const mutationKey = ["deleteApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteApplication>>,
        { id: UlidId }
    > = (props) => {
        const { id } = props ?? {};

        return deleteApplication(id, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteApplication>>
>;

export type DeleteApplicationMutationError = ApiError;

/**
 * @summary Delete an existing oauth application
 */
export const createDeleteApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof deleteApplication>>,
            TError,
            { id: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof deleteApplication>>,
    TError,
    { id: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getDeleteApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type editApplicationResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type editApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type editApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type editApplicationResponseSuccess = editApplicationResponse200 & {
    headers: Headers;
};
export type editApplicationResponseError = (
    | editApplicationResponse404
    | editApplicationResponse500
) & {
    headers: Headers;
};

export type editApplicationResponse = editApplicationResponseSuccess | editApplicationResponseError;

export const getEditApplicationUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/oauth/application/${id}`;
};

/**
 * @summary Update an existing oauth application
 */
export const editApplication = async (
    id: UlidId,
    oauthApplicationData: OauthApplicationData,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<editApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getEditApplicationUrl(id), {
        credentials: "include",
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(oauthApplicationData)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: editApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as editApplicationResponse;
};

export const getEditApplicationMutationOptions = <TError = ApiError, TContext = unknown>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof editApplication>>,
        TError,
        { id: UlidId; data: OauthApplicationData },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof editApplication>>,
    TError,
    { id: UlidId; data: OauthApplicationData },
    TContext
> => {
    const mutationKey = ["editApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof editApplication>>,
        { id: UlidId; data: OauthApplicationData }
    > = (props) => {
        const { id, data } = props ?? {};

        return editApplication(id, data, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type EditApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof editApplication>>
>;
export type EditApplicationMutationBody = OauthApplicationData;
export type EditApplicationMutationError = ApiError;

/**
 * @summary Update an existing oauth application
 */
export const createEditApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof editApplication>>,
            TError,
            { id: UlidId; data: OauthApplicationData },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof editApplication>>,
    TError,
    { id: UlidId; data: OauthApplicationData },
    TContext
> => {
    return createMutation(
        () => ({ ...getEditApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type rotateSecretApplicationResponse200 = {
    data: OauthApplicationDataResponse;
    status: 200;
};

export type rotateSecretApplicationResponse404 = {
    data: ApiError;
    status: 404;
};

export type rotateSecretApplicationResponse500 = {
    data: ApiError;
    status: 500;
};

export type rotateSecretApplicationResponseSuccess = rotateSecretApplicationResponse200 & {
    headers: Headers;
};
export type rotateSecretApplicationResponseError = (
    | rotateSecretApplicationResponse404
    | rotateSecretApplicationResponse500
) & {
    headers: Headers;
};

export type rotateSecretApplicationResponse =
    | rotateSecretApplicationResponseSuccess
    | rotateSecretApplicationResponseError;

export const getRotateSecretApplicationUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/oauth/application/${id}/rotate_keys`;
};

/**
 * @summary Rotate the secret of an existing oauth application
 */
export const rotateSecretApplication = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<rotateSecretApplicationResponse> => {
    const res = await (fetchFn ?? fetch)(getRotateSecretApplicationUrl(id), {
        credentials: "include",
        ...options,
        method: "PATCH"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: rotateSecretApplicationResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as rotateSecretApplicationResponse;
};

export const getRotateSecretApplicationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof rotateSecretApplication>>,
        TError,
        { id: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof rotateSecretApplication>>,
    TError,
    { id: UlidId },
    TContext
> => {
    const mutationKey = ["rotateSecretApplication"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof rotateSecretApplication>>,
        { id: UlidId }
    > = (props) => {
        const { id } = props ?? {};

        return rotateSecretApplication(id, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type RotateSecretApplicationMutationResult = NonNullable<
    Awaited<ReturnType<typeof rotateSecretApplication>>
>;

export type RotateSecretApplicationMutationError = ApiError;

/**
 * @summary Rotate the secret of an existing oauth application
 */
export const createRotateSecretApplication = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof rotateSecretApplication>>,
            TError,
            { id: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof rotateSecretApplication>>,
    TError,
    { id: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getRotateSecretApplicationMutationOptions(options?.()) }),
        queryClient
    );
};
export type listOauthAuthorizationsResponse200 = {
    data: ListDataResponseOauthApplication;
    status: 200;
};

export type listOauthAuthorizationsResponse500 = {
    data: ApiError;
    status: 500;
};

export type listOauthAuthorizationsResponseSuccess = listOauthAuthorizationsResponse200 & {
    headers: Headers;
};
export type listOauthAuthorizationsResponseError = listOauthAuthorizationsResponse500 & {
    headers: Headers;
};

export type listOauthAuthorizationsResponse =
    | listOauthAuthorizationsResponseSuccess
    | listOauthAuthorizationsResponseError;

export const getListOauthAuthorizationsUrl = (params?: ListOauthAuthorizationsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `${apiUrlForOrval}/v1/me/oauth/authorization/list?${stringifiedParams}`
        : `${apiUrlForOrval}/v1/me/oauth/authorization/list`;
};

/**
 * @summary List your oauth authorizations
 */
export const listOauthAuthorizations = async (
    params?: ListOauthAuthorizationsParams,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<listOauthAuthorizationsResponse> => {
    const res = await (fetchFn ?? fetch)(getListOauthAuthorizationsUrl(params), {
        credentials: "include",
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: listOauthAuthorizationsResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as listOauthAuthorizationsResponse;
};

export const getListOauthAuthorizationsQueryKey = (params?: ListOauthAuthorizationsParams) => {
    return [
        `${apiUrlForOrval}/v1/me/oauth/authorization/list`,
        ...(params ? [params] : [])
    ] as const;
};

export const getListOauthAuthorizationsQueryOptions = <
    TData = Awaited<ReturnType<typeof listOauthAuthorizations>>,
    TError = ApiError
>(
    params?: ListOauthAuthorizationsParams,
    options?: {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof listOauthAuthorizations>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    }
) => {
    const { query: queryOptions, fetch: fetchOptions, fetcher: fetcherFn } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getListOauthAuthorizationsQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listOauthAuthorizations>>> = ({
        signal
    }) => listOauthAuthorizations(params, { signal, ...fetchOptions }, fetcherFn);

    return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
        Awaited<ReturnType<typeof listOauthAuthorizations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListOauthAuthorizationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof listOauthAuthorizations>>
>;
export type ListOauthAuthorizationsQueryError = ApiError;

/**
 * @summary List your oauth authorizations
 */

export function createListOauthAuthorizations<
    TData = Awaited<ReturnType<typeof listOauthAuthorizations>>,
    TError = ApiError
>(
    params?: () => ListOauthAuthorizationsParams,
    options?: () => {
        query?: Partial<
            CreateQueryOptions<Awaited<ReturnType<typeof listOauthAuthorizations>>, TError, TData>
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const query = createQuery(
        () => getListOauthAuthorizationsQueryOptions(params?.(), options?.()),
        queryClient
    ) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return query;
}

export type deleteOauthAuthorizationResponse200 = {
    data: AlrightResponse;
    status: 200;
};

export type deleteOauthAuthorizationResponse404 = {
    data: ApiError;
    status: 404;
};

export type deleteOauthAuthorizationResponse500 = {
    data: ApiError;
    status: 500;
};

export type deleteOauthAuthorizationResponseSuccess = deleteOauthAuthorizationResponse200 & {
    headers: Headers;
};
export type deleteOauthAuthorizationResponseError = (
    | deleteOauthAuthorizationResponse404
    | deleteOauthAuthorizationResponse500
) & {
    headers: Headers;
};

export type deleteOauthAuthorizationResponse =
    | deleteOauthAuthorizationResponseSuccess
    | deleteOauthAuthorizationResponseError;

export const getDeleteOauthAuthorizationUrl = (id: UlidId) => {
    return `${apiUrlForOrval}/v1/me/oauth/authorization/${id}`;
};

/**
 * @summary Revoke an oauth authorization
 */
export const deleteOauthAuthorization = async (
    id: UlidId,
    options?: RequestInit,
    fetchFn?: typeof globalThis.fetch
): Promise<deleteOauthAuthorizationResponse> => {
    const res = await (fetchFn ?? fetch)(getDeleteOauthAuthorizationUrl(id), {
        credentials: "include",
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: deleteOauthAuthorizationResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as deleteOauthAuthorizationResponse;
};

export const getDeleteOauthAuthorizationMutationOptions = <
    TError = ApiError,
    TContext = unknown
>(options?: {
    mutation?: CreateMutationOptions<
        Awaited<ReturnType<typeof deleteOauthAuthorization>>,
        TError,
        { id: UlidId },
        TContext
    >;
    fetch?: RequestInit;
    fetcher?: typeof globalThis.fetch;
}): CreateMutationOptions<
    Awaited<ReturnType<typeof deleteOauthAuthorization>>,
    TError,
    { id: UlidId },
    TContext
> => {
    const mutationKey = ["deleteOauthAuthorization"];
    const {
        mutation: mutationOptions,
        fetch: fetchOptions,
        fetcher: fetcherFn
    } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteOauthAuthorization>>,
        { id: UlidId }
    > = (props) => {
        const { id } = props ?? {};

        return deleteOauthAuthorization(id, fetchOptions, fetcherFn);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteOauthAuthorizationMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteOauthAuthorization>>
>;

export type DeleteOauthAuthorizationMutationError = ApiError;

/**
 * @summary Revoke an oauth authorization
 */
export const createDeleteOauthAuthorization = <TError = ApiError, TContext = unknown>(
    options?: () => {
        mutation?: CreateMutationOptions<
            Awaited<ReturnType<typeof deleteOauthAuthorization>>,
            TError,
            { id: UlidId },
            TContext
        >;
        fetch?: RequestInit;
        fetcher?: typeof globalThis.fetch;
    },
    queryClient?: () => QueryClient
): CreateMutationResult<
    Awaited<ReturnType<typeof deleteOauthAuthorization>>,
    TError,
    { id: UlidId },
    TContext
> => {
    return createMutation(
        () => ({ ...getDeleteOauthAuthorizationMutationOptions(options?.()) }),
        queryClient
    );
};
